# Примеры решения универсальной задачи "обоснованного выбора лучшего из двух вариантов"

**Для запуска вычислений, в секретах (Keys) этого .ipynb ноутбука необходимо задать значения следующих переменных:**
- `OPENAI_BASE_URL` (пример: `https://api.deepseek.com`)
- `OPENAI_API_KEY` (пример: `sk-...`)
- `OPENAI_MODEL` (пример: `deepseek-chat`)

## Настройка среды, вспомогательных функций и общих переменных для вычисления

Установка зависимостей и пакета [core-kbt](https://https://github.com/ady1981/core-kbt):

In [1]:
!pip install -q poetry
!poetry config virtualenvs.in-project false
!rm -r /content/core-kbt
%cd /content
!git clone https://github.com/ady1981/core-kbt
%cd /content/core-kbt
!mv -n /content/core-kbt/processes /content/processes ## Keep cache of process results separately in /content/processes
!rm -r /content/core-kbt/processes
!ln -s /content/processes /content/core-kbt/processes ## Link to the cache
!pip install ruamel.yaml
!poetry install

/content
Cloning into 'core-kbt'...
remote: Enumerating objects: 1517, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 1517 (delta 14), reused 20 (delta 11), pack-reused 1489 (from 1)
Receiving objects: 100% (1517/1517), 309.63 KiB | 2.20 MiB/s, done.
Resolving deltas: 100% (905/905), done.
/content/core-kbt
Requirement already satisfied: ruamel.yaml in /usr/local/lib/python3.12/dist-packages (0.19.1)
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: kbt_core (0.2.8)Installing the current project: kbt_core (0.2.8)

Установка дополнительных параметров для вычисления:

In [2]:
frame_of_reference = 'Unbiased logic framework'
output_content_language = 'Russian'
extra_information_retrieval_strategy = 'Only_unbiased_authorative_sources: true'

Установка переменных среды для openAI-compatible API:

In [3]:
import os
from google.colab import userdata
os.environ['OPENAI_BASE_URL'] = userdata.get('OPENAI_BASE_URL')
os.environ['OPENAI_MODEL'] = userdata.get('OPENAI_MODEL') ## Название LLM модели
os.environ['OPENAI_API_KEY'] = userdata.get('OPENAI_API_KEY')

Вспомогательные функции для вычисления:

In [4]:
import asyncio
import os
import pandas as pd
from google.colab import data_table

from kbt_core.ai_function import evaluate_function
from kbt_core.common import with_model_input_data, get_float

data_table.enable_dataframe_formatter()

async def calc_concept_aspect_comparison(observer_context_description, a_concept, b_concept, frame_of_reference, output_content_language, extra_information_retrieval_strategy):
    input_data = {
        'observer_context_description': observer_context_description,
        'a_concept': a_concept,
        'b_concept': b_concept,
        'frame_of_reference': frame_of_reference,
        'output_content_language': output_content_language,
        'extra_information_retrieval_strategy': extra_information_retrieval_strategy
    }
    return await evaluate_function('concept_aspect_comparison', with_model_input_data(input_data, os.environ['OPENAI_MODEL']))

def create_output_tables(result, observer_context_description, a_concept, b_concept):
  llm_model = os.environ['OPENAI_MODEL']
  total_cols = {
      'result_name': ['comparison_winner', 'a_concept_score', 'b_concept_score', 'LLM_model', 'superordinate_concept', 'perspective_observer_strategy', 'point_of_view', 'observer_context_description', 'a_concept', 'b_concept'],
      'result_value':
        [result['comparison_winner'],
          f'{round(result["comparison_total"] * 100)}%',
          f'{round(-result["comparison_total"] * 100)}%',
         llm_model] +
          [result[c] for c in ['superordinate_concept', 'perspective_observer_strategy', 'point_of_view']] +
          [observer_context_description, a_concept, b_concept]
      }
  aspect_cols = [{'type': 'feature_score',
  'aspect': aspect['aspect_name'],
  'feature': feature['feature_name'],
  'a_concept_winner': get_float(feature, 'comparison', 0) > 0,
  'a_concept_score': f'{round(feature["normalized_comparison"] * 100)}%' if get_float(feature, 'comparison', 0) > 0 else '-',
  'b_concept_winner': get_float(feature, 'comparison', 0) < 0,
  'b_concept_score': f'{round(-feature["normalized_comparison"] * 100)}%' if get_float(feature, 'comparison', 0) < 0 else '-'}
      for aspect in result['perspective_aspects']
      for feature in aspect['aspect_features']]
  total_dt = pd.DataFrame(total_cols)
  aspect_dt = pd.DataFrame(aspect_cols)
  return (total_dt, aspect_dt)

## Пример №1: Выбор оптимального фреймворка для разработки нового микросервиса

In [5]:
d01_observer_context_description = 'Владельцу продукта необходимо выбрать оптимальный фреймворк для разработки нового микросервиса среднего размера, обеспечив его запуск в течение 60 календарных дней. Приоритетными целями являются максимальная скорость итеративной разработки.'
d01_a_concept = 'FastAPI (Python)'
d01_b_concept = 'Gin (Go)'
d01_result = await calc_concept_aspect_comparison(d01_observer_context_description, d01_a_concept, d01_b_concept, frame_of_reference, output_content_language, extra_information_retrieval_strategy)
(d01_total_dt, d01_aspect_dt) = create_output_tables(d01_result, d01_observer_context_description, d01_a_concept, d01_b_concept)

start: input_id=superordinate_concept_identification_af.1.7c4b139220d16dcec6ab5e8be56c4348.4c4c4a17ef0816e595c3755977f91d04
process:
{"concepts": "- FastAPI (Python)\n- Gin (Go)", "context_knowledge_specification": "### Context description\n\u0412\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0443 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430 \u043d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e \u0432\u044b\u0431\u0440\u0430\u0442\u044c \u043e\u043f\u0442\u0438\u043c\u0430\u043b\u044c\u043d\u044b\u0439 \u0444\u0440\u0435\u0439\u043c\u0432\u043e\u0440\u043a \u0434\u043b\u044f \u0440\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u043a\u0438 \u043d\u043e\u0432\u043e\u0433\u043e \u043c\u0438\u043a\u0440\u043e\u0441\u0435\u0440\u0432\u0438\u0441\u0430 \u0441\u0440\u0435\u0434\u043d\u0435\u0433\u043e \u0440\u0430\u0437\u043c\u0435\u0440\u0430, \u043e\u0431\u0435\u0441\u043f\u0435\u0447\u0438\u0432 \u0435\u0433\u043e \u0437\u0430\u043f\u0443\u0441\u043a \u0432 \u0442\u0435\u0447\u0435\u043d\u0438\u0435 60 \u043a\u0430\u043b\u0435\u043d\u0434\u0430\u0440\u043d\u044b\u0445 \u0434\u043d\u0435\u0439. \u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442\u043d\u044b\u043c\u0438 \u0446\u0435\u043b\u044f\u043c\u0438 \u044f\u0432\u043b\u044f\u044e\u0442\u0441\u044f \u043c\u0430\u043a\u0441\u0438\u043c\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u043a\u043e\u0440\u043e\u0441\u0442\u044c \u0438\u0442\u0435\u0440\u0430\u0442\u0438\u0432\u043d\u043e\u0439 \u0440\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u043a\u0438.", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "superordinate_concept_identification_af", "input_id": "superordinate_concept_identification_af.1.7c4b139220d16dcec6ab5e8be56c4348.4c4c4a17ef0816e595c3755977f91d04"}
end: input_id=superordinate_concept_identification_af.1.7c4b139220d16dcec6ab5e8be56c4348.4c4c4a17ef0816e595c3755977f91d04
other_notes: Both FastAPI (Python) and Gin (Go) are modern, high-performance web frameworks designed for building APIs and microservices. They share the superordinate concept of being tools for backend web development, specifically within the context of the given task for microservice creation under time constraints.
start: input_id=perspective_features_af.1.7c4b139220d16dcec6ab5e8be56c4348.a23155b30e9aa3030a7969ac06182b36
process:
{"concept": "Web Application Frameworks", "observer_context_description": "\u0412\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0443 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430 \u043d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e \u0432\u044b\u0431\u0440\u0430\u0442\u044c \u043e\u043f\u0442\u0438\u043c\u0430\u043b\u044c\u043d\u044b\u0439 \u0444\u0440\u0435\u0439\u043c\u0432\u043e\u0440\u043a \u0434\u043b\u044f \u0440\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u043a\u0438 \u043d\u043e\u0432\u043e\u0433\u043e \u043c\u0438\u043a\u0440\u043e\u0441\u0435\u0440\u0432\u0438\u0441\u0430 \u0441\u0440\u0435\u0434\u043d\u0435\u0433\u043e \u0440\u0430\u0437\u043c\u0435\u0440\u0430, \u043e\u0431\u0435\u0441\u043f\u0435\u0447\u0438\u0432 \u0435\u0433\u043e \u0437\u0430\u043f\u0443\u0441\u043a \u0432 \u0442\u0435\u0447\u0435\u043d\u0438\u0435 60 \u043a\u0430\u043b\u0435\u043d\u0434\u0430\u0440\u043d\u044b\u0445 \u0434\u043d\u0435\u0439. \u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442\u043d\u044b\u043c\u0438 \u0446\u0435\u043b\u044f\u043c\u0438 \u044f\u0432\u043b\u044f\u044e\u0442\u0441\u044f \u043c\u0430\u043a\u0441\u0438\u043c\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u043a\u043e\u0440\u043e\u0441\u0442\u044c \u0438\u0442\u0435\u0440\u0430\u0442\u0438\u0432\u043d\u043e\u0439 \u0440\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u043a\u0438.", "frame_of_reference": "Unbiased logic framework", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_features_af", "input_id": "perspective_features_af.1.7c4b139220d16dcec6ab5e8be56c4348.a23155b30e9aa3030a7969ac06182b36"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to retrieve perspective aspects for a given Concept and specified perspective frame of reference, perspective observer strategy and point of view.
Identify the perspective observer strategy and the point of view from a given observer context description.
## Concept
Web Application Frameworks
## Observer conte ...

end: input_id=perspective_features_af.1.7c4b139220d16dcec6ab5e8be56c4348.a23155b30e9aa3030a7969ac06182b36
other_notes: Аспекты и их важность определены исходя из приоритета скорости итеративной разработки и жесткого ограничения по времени (60 дней). В рамках беспристрастной логической системы оценка важности аспектов производится относительно друг друга, где аспект скорости разработки получает наивысший приоритет. Особенности (features) внутри каждого аспекта также ранжированы по важности для данного ракурса.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.a7e9a5a6b2da699c45461305ee5314ba
process:
{"a_concept": "FastAPI (Python)", "b_concept": "Gin (Go)", "aspect_name": "\u0421\u043a\u043e\u0440\u043e\u0441\u0442\u044c \u0440\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u043a\u0438 \u0438 \u0438\u0442\u0435\u0440\u0430\u0446\u0438\u0439", "aspect_features": "- \u0423\u0440\u043e\u0432\u0435\u043d\u044c \u0430\u0431\u0441\u0442\u0440\u0430\u043a\u0446\u0438\u0438 \u0438 \u0432\u0441\u0442\u0440\u043e\u0435\u043d\u043d\u044b\u0435 \u0432\u043e\u0437\u043c\u043e\u0436\u043d\u043e\u0441\u0442\u0438\n- \u041a\u0430\u0447\u0435\u0441\u0442\u0432\u043e \u0438 \u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e\u0441\u0442\u044c \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430\u0446\u0438\u0438\n- \u0420\u0430\u0437\u043c\u0435\u0440 \u0438 \u0430\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c \u0441\u043e\u043e\u0431\u0449\u0435\u0441\u0442\u0432\u0430\n- \u041a\u0440\u0438\u0432\u0430\u044f \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f \u0434\u043b\u044f \u043a\u043e\u043c\u0430\u043d\u0434\u044b", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "Product Owner with Time-to-Market and Iterative Development Focus", "point_of_view": "Decision-maker selecting a framework for a medium-sized microservice under a 60-day launch constraint", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.a7e9a5a6b2da699c45461305ee5314ba"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
FastAPI (Python)
## Concept B
Gin (Go)
## Aspect name
Скорость разработки и итераций
## Aspect features
- Уровень абстракции и встроенные возможности
- Качество ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.a7e9a5a6b2da699c45461305ee5314ba
other_notes: С точки зрения Product Owner с фокусом на Time-to-Market и итеративную разработку для микросервиса среднего размера с ограничением в 60 дней, FastAPI (Python) демонстрирует явные преимущества по всем указанным аспектам, связанным со скоростью разработки. Высокий уровень абстракции, автоматическая генерация документации, большое активное сообщество и низкая кривая обучения для команд, знакомых с Python, способствуют более быстрому достижению результата. Gin (Go), будучи производительным и минималистичным фреймворком, требует большего объема ручного кодирования и, как правило, более крутой кривой обучения для команд, не имеющих опыта работы с Go, что может замедлить начальные итерации в условиях жестких временных ограничений.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.efb65581f31ac459c8c8837c018791b1
process:
{"a_concept": "FastAPI (Python)", "b_concept": "Gin (Go)", "aspect_name": "\u0421\u043e\u043e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0438\u0435 \u0430\u0440\u0445\u0438\u0442\u0435\u043a\u0442\u0443\u0440\u043d\u044b\u043c \u0442\u0440\u0435\u0431\u043e\u0432\u0430\u043d\u0438\u044f\u043c \u043c\u0438\u043a\u0440\u043e\u0441\u0435\u0440\u0432\u0438\u0441\u0430", "aspect_features": "- \u0412\u0441\u0442\u0440\u043e\u0435\u043d\u043d\u0430\u044f \u043f\u043e\u0434\u0434\u0435\u0440\u0436\u043a\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f API\n- \u041c\u043e\u0434\u0443\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u0438 \u043b\u0435\u0433\u043a\u043e\u0441\u0442\u044c \u0440\u0430\u0437\u0432\u0435\u0440\u0442\u044b\u0432\u0430\u043d\u0438\u044f\n- \u0418\u043d\u0442\u0435\u0433\u0440\u0430\u0446\u0438\u044f \u0441 \u0441\u0438\u0441\u0442\u0435\u043c\u0430\u043c\u0438 \u043c\u043e\u043d\u0438\u0442\u043e\u0440\u0438\u043d\u0433\u0430 \u0438 \u043b\u043e\u0433\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "Product Owner with Time-to-Market and Iterative Development Focus", "point_of_view": "Decision-maker selecting a framework for a medium-sized microservice under a 60-day launch constraint", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.efb65581f31ac459c8c8837c018791b1"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
FastAPI (Python)
## Concept B
Gin (Go)
## Aspect name
Соответствие архитектурным требованиям микросервиса
## Aspect features
- Встроенная поддержка создания API ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.efb65581f31ac459c8c8837c018791b1
other_notes: С точки зрения Product Owner с фокусом на Time-to-Market и итеративную разработку, FastAPI (Python) предлагает более быстрый старт благодаря автоматической генерации документации (OpenAPI) и встроенной валидации данных, что ускоряет разработку API. Gin (Go) обеспечивает более высокую производительность и меньший размер исполняемого файла, что упрощает развертывание и масштабирование микросервиса. Оба фреймворка хорошо интегрируются с экосистемой мониторинга и логирования своих языков (например, Prometheus для Go, структурированное логирование для Python), поэтому выбор может зависеть от предпочтений команды и требований к производительности. В условиях ограничения в 60 дней, FastAPI может быть предпочтительнее для команд, знакомых с Python, из-за скорости разработки, в то время как Gin может быть лучше для требовательных к производительности сервисов, где важна скорость выполнения и эффективность ресурсов.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.d226f216382f9c7892fbccd70016abf3
process:
{"a_concept": "FastAPI (Python)", "b_concept": "Gin (Go)", "aspect_name": "\u042d\u043a\u043e\u0441\u0438\u0441\u0442\u0435\u043c\u0430 \u0438 \u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e\u0441\u0442\u044c \u0433\u043e\u0442\u043e\u0432\u044b\u0445 \u0440\u0435\u0448\u0435\u043d\u0438\u0439", "aspect_features": "- \u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u0438 \u043a\u0430\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0430\u043a\u0435\u0442\u043e\u0432/\u0431\u0438\u0431\u043b\u0438\u043e\u0442\u0435\u043a \u0434\u043b\u044f \u0442\u0438\u043f\u043e\u0432\u044b\u0445 \u0437\u0430\u0434\u0430\u0447\n- \u0418\u043d\u0442\u0435\u0433\u0440\u0430\u0446\u0438\u044f \u0441\u043e \u0441\u0442\u043e\u0440\u043e\u043d\u043d\u0438\u043c\u0438 \u0441\u0435\u0440\u0432\u0438\u0441\u0430\u043c\u0438 (\u0431\u0430\u0437\u044b \u0434\u0430\u043d\u043d\u044b\u0445, \u043e\u0447\u0435\u0440\u0435\u0434\u0438, \u043a\u044d\u0448\u0438)", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "Product Owner with Time-to-Market and Iterative Development Focus", "point_of_view": "Decision-maker selecting a framework for a medium-sized microservice under a 60-day launch constraint", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.d226f216382f9c7892fbccd70016abf3"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
FastAPI (Python)
## Concept B
Gin (Go)
## Aspect name
Экосистема и доступность готовых решений
## Aspect features
- Наличие и качество пакетов/библиотек для тип ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.d226f216382f9c7892fbccd70016abf3
other_notes: С точки зрения Product Owner с фокусом на Time-to-Market и итеративную разработку для микросервиса со сроком запуска 60 дней, экосистема Python (FastAPI) предоставляет более обширный и зрелый набор готовых решений (ORM, драйверы БД, клиенты для очередей), что ускоряет разработку. Экосистема Go (Gin) также имеет качественные библиотеки, но их выбор и зрелость для некоторых типовых задач могут быть меньше, что может потребовать больше времени на интеграцию или реализацию собственных решений.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.226dd992bbe463428795ce14caf584d0
process:
{"a_concept": "FastAPI (Python)", "b_concept": "Gin (Go)", "aspect_name": "\u0414\u043e\u043b\u0433\u043e\u0441\u0440\u043e\u0447\u043d\u0430\u044f \u043f\u043e\u0434\u0434\u0435\u0440\u0436\u0438\u0432\u0430\u0435\u043c\u043e\u0441\u0442\u044c \u0438 \u0441\u0442\u0430\u0431\u0438\u043b\u044c\u043d\u043e\u0441\u0442\u044c", "aspect_features": "- \u0421\u0442\u0430\u0431\u0438\u043b\u044c\u043d\u043e\u0441\u0442\u044c API \u0444\u0440\u0435\u0439\u043c\u0432\u043e\u0440\u043a\u0430\n- \u041f\u043e\u043b\u0438\u0442\u0438\u043a\u0430 \u0438 \u0447\u0430\u0441\u0442\u043e\u0442\u0430 \u0432\u044b\u043f\u0443\u0441\u043a\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u0439\n- \u0414\u043e\u0441\u0442\u0443\u043f\u043d\u043e\u0441\u0442\u044c \u043a\u043e\u043c\u043c\u0435\u0440\u0447\u0435\u0441\u043a\u043e\u0439 \u043f\u043e\u0434\u0434\u0435\u0440\u0436\u043a\u0438", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "Product Owner with Time-to-Market and Iterative Development Focus", "point_of_view": "Decision-maker selecting a framework for a medium-sized microservice under a 60-day launch constraint", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.226dd992bbe463428795ce14caf584d0"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
FastAPI (Python)
## Concept B
Gin (Go)
## Aspect name
Долгосрочная поддерживаемость и стабильность
## Aspect features
- Стабильность API фреймворка
- Политика и ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.226dd992bbe463428795ce14caf584d0
other_notes: С точки зрения Product Owner с фокусом на Time-to-Market и итеративную разработку, оба фреймворка обеспечивают высокую скорость разработки. Однако, в контексте долгосрочной поддерживаемости и стабильности для микросервиса со сроком запуска 60 дней, Gin (Go) демонстрирует преимущество благодаря более стабильному API и предсказуемому циклу релизов, что снижает риски рефакторинга. FastAPI, будучи активно развивающимся проектом, может иметь более частые изменения. Коммерческая поддержка для обоих в основном доступна через консалтинговые компании или подрядчиков, а не через официальные корпоративные планы поддержки, что делает их сопоставимыми в этом аспекте. Дополнительные аспекты для рассмотрения: зрелость экосистемы языка (Go vs Python), простота развертывания и мониторинга, которые также влияют на долгосрочную поддерживаемость.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.88ba51433b4575b0a635150592e0b995
process:
{"a_concept": "FastAPI (Python)", "b_concept": "Gin (Go)", "aspect_name": "\u041f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u0438 \u044d\u0444\u0444\u0435\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u044f \u0440\u0435\u0441\u0443\u0440\u0441\u043e\u0432", "aspect_features": "- \u041f\u043e\u0442\u0440\u0435\u0431\u043b\u0435\u043d\u0438\u0435 \u043f\u0430\u043c\u044f\u0442\u0438\n- \u0421\u043a\u043e\u0440\u043e\u0441\u0442\u044c \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0438 \u0437\u0430\u043f\u0440\u043e\u0441\u043e\u0432\n- \u0412\u0440\u0435\u043c\u044f \u0437\u0430\u043f\u0443\u0441\u043a\u0430 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u044f", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "Product Owner with Time-to-Market and Iterative Development Focus", "point_of_view": "Decision-maker selecting a framework for a medium-sized microservice under a 60-day launch constraint", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.88ba51433b4575b0a635150592e0b995"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:

In [6]:
d01_total_dt

,result_name,result_value
0,comparison_winner,FastAPI (Python)
1,a_concept_score,18%
2,b_concept_score,-18%
3,LLM_model,deepseek/deepseek-chat
4,superordinate_concept,Web Application Frameworks
5,perspective_observer_strategy,Product Owner with Time-to-Market and Iterativ...
6,point_of_view,Decision-maker selecting a framework for a med...
7,observer_context_description,Владельцу продукта необходимо выбрать оптималь...
8,a_concept,FastAPI (Python)
9,b_concept,Gin (Go)

In [7]:
d01_aspect_dt

,type,aspect,feature,a_concept_winner,a_concept_score,b_concept_winner,b_concept_score
0,feature_score,Скорость разработки и итераций,Уровень абстракции и встроенные возможности,True,7%,False,-
1,feature_score,Скорость разработки и итераций,Качество и доступность документации,True,6%,False,-
2,feature_score,Скорость разработки и итераций,Размер и активность сообщества,True,6%,False,-
3,feature_score,Скорость разработки и итераций,Кривая обучения для команды,True,5%,False,-
4,feature_score,Соответствие архитектурным требованиям микросе...,Встроенная поддержка создания API,True,8%,False,-
5,feature_score,Соответствие архитектурным требованиям микросе...,Модульность и легкость развертывания,False,-,True,8%
6,feature_score,Соответствие архитектурным требованиям микросе...,Интеграция с системами мониторинга и логирования,False,-,False,-
7,feature_score,Экосистема и доступность готовых решений,Наличие и качество пакетов/библиотек для типов...,True,11%,False,-
8,feature_score,Экосистема и доступность готовых решений,Интеграция со сторонними сервисами (базы данны...,True,9%,False,-
9,feature_score,Долгосрочная поддерживаемость и стабильность,Стабильность API фреймворка,False,-,True,7%
10,feature_score,Долгосрочная поддерживаемость и стабильность,Политика и частота выпуска обновлений,False,-,True,6%
11,feature_score,Долгосрочная поддерживаемость и стабильность,Доступность коммерческой поддержки,False,-,False,-
12,feature_score,Производительность и эффективность использован...,Потребление памяти,False,-,True,6%
13,feature_score,Производительность и эффективность использован...,Скорость обработки запросов,False,-,True,5%
14,feature_score,Производительность и эффективность использован...,Время запуска приложения,False,-,True,4%

## Пример №2. Выбор лучшего метода хранения данных для долгосрочного архива

In [8]:
d02_observer_context_description = 'Крупная организация (архив) должна выбрать, какой формат использовать для хранения цифровых копий исторических документов на следующие 100 лет, с акцентом на долговечность и независимость от проприетарного ПО.'
d02_a_concept = 'PDF'
d02_b_concept = 'TIFF'
d02_result = await calc_concept_aspect_comparison(d02_observer_context_description, d02_a_concept, d02_b_concept, frame_of_reference, output_content_language, extra_information_retrieval_strategy)
(d02_total_dt, d02_aspect_dt) = create_output_tables(d02_result, d02_observer_context_description, d02_a_concept, d02_b_concept)

start: input_id=superordinate_concept_identification_af.1.7c4b139220d16dcec6ab5e8be56c4348.1bc5be3867816d67525718051160b9f5
process:
{"concepts": "- PDF\n- TIFF", "context_knowledge_specification": "### Context description\n\u041a\u0440\u0443\u043f\u043d\u0430\u044f \u043e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f (\u0430\u0440\u0445\u0438\u0432) \u0434\u043e\u043b\u0436\u043d\u0430 \u0432\u044b\u0431\u0440\u0430\u0442\u044c, \u043a\u0430\u043a\u043e\u0439 \u0444\u043e\u0440\u043c\u0430\u0442 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0434\u043b\u044f \u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u0446\u0438\u0444\u0440\u043e\u0432\u044b\u0445 \u043a\u043e\u043f\u0438\u0439 \u0438\u0441\u0442\u043e\u0440\u0438\u0447\u0435\u0441\u043a\u0438\u0445 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u043e\u0432 \u043d\u0430 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0438\u0435 100 \u043b\u0435\u0442, \u0441 \u0430\u043a\u0446\u0435\u043d\u0442\u043e\u043c \u043d\u0430 \u0434\u043e\u043b\u0433\u043e\u0432\u0435\u0447\u043d\u043e\u0441\u0442\u044c \u0438 \u043d\u0435\u0437\u0430\u0432\u0438\u0441\u0438\u043c\u043e\u0441\u0442\u044c \u043e\u0442 \u043f\u0440\u043e\u043f\u0440\u0438\u0435\u0442\u0430\u0440\u043d\u043e\u0433\u043e \u041f\u041e.", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "superordinate_concept_identification_af", "input_id": "superordinate_concept_identification_af.1.7c4b139220d16dcec6ab5e8be56c4348.1bc5be3867816d67525718051160b9f5"}
end: input_id=superordinate_concept_identification_af.1.7c4b139220d16dcec6ab5e8be56c4348.1bc5be3867816d67525718051160b9f5
other_notes: Both PDF and TIFF are specific types of file formats used for storing digital documents and images. In the context of long-term archival of historical documents, the superordinate concept 'raster image file format' is particularly relevant as it emphasizes the pixel-based nature common to many archival TIFFs and the image layers within PDFs, which is a key consideration for format longevity and software independence.
start: input_id=perspective_features_af.1.7c4b139220d16dcec6ab5e8be56c4348.43179bc4c39ab18bdbfe5d2439f51228
process:
{"concept": "Raster image file format", "observer_context_description": "\u041a\u0440\u0443\u043f\u043d\u0430\u044f \u043e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u044f (\u0430\u0440\u0445\u0438\u0432) \u0434\u043e\u043b\u0436\u043d\u0430 \u0432\u044b\u0431\u0440\u0430\u0442\u044c, \u043a\u0430\u043a\u043e\u0439 \u0444\u043e\u0440\u043c\u0430\u0442 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0434\u043b\u044f \u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u0446\u0438\u0444\u0440\u043e\u0432\u044b\u0445 \u043a\u043e\u043f\u0438\u0439 \u0438\u0441\u0442\u043e\u0440\u0438\u0447\u0435\u0441\u043a\u0438\u0445 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u043e\u0432 \u043d\u0430 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0438\u0435 100 \u043b\u0435\u0442, \u0441 \u0430\u043a\u0446\u0435\u043d\u0442\u043e\u043c \u043d\u0430 \u0434\u043e\u043b\u0433\u043e\u0432\u0435\u0447\u043d\u043e\u0441\u0442\u044c \u0438 \u043d\u0435\u0437\u0430\u0432\u0438\u0441\u0438\u043c\u043e\u0441\u0442\u044c \u043e\u0442 \u043f\u0440\u043e\u043f\u0440\u0438\u0435\u0442\u0430\u0440\u043d\u043e\u0433\u043e \u041f\u041e.", "frame_of_reference": "Unbiased logic framework", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_features_af", "input_id": "perspective_features_af.1.7c4b139220d16dcec6ab5e8be56c4348.43179bc4c39ab18bdbfe5d2439f51228"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to retrieve perspective aspects for a given Concept and specified perspective frame of reference, perspective observer strategy and point of view.
Identify the perspective observer strategy and the point of view from a given observer context description.
## Concept
Raster image file format
## Observer context ...

end: input_id=perspective_features_af.1.7c4b139220d16dcec6ab5e8be56c4348.43179bc4c39ab18bdbfe5d2439f51228
other_notes: Аспекты и их важность определены строго с точки зрения задачи долгосрочного архивного хранения исторических документов на 100 лет. Наибольший вес имеют критерии, обеспечивающие доступность и читаемость данных в далеком будущем, независимо от развития технологий и коммерческого ПО.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.452e97392afb3212f14b629caebc5d50
process:
{"a_concept": "PDF", "b_concept": "TIFF", "aspect_name": "\u0414\u043e\u043b\u0433\u043e\u0432\u0435\u0447\u043d\u043e\u0441\u0442\u044c \u0438 \u0441\u0442\u0430\u0431\u0438\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u0444\u043e\u0440\u043c\u0430\u0442\u0430", "aspect_features": "- \u0421\u0442\u0430\u043d\u0434\u0430\u0440\u0442\u0438\u0437\u0430\u0446\u0438\u044f\n- \u0421\u043b\u043e\u0436\u043d\u043e\u0441\u0442\u044c \u0444\u043e\u0440\u043c\u0430\u0442\u0430\n- \u0418\u0441\u0442\u043e\u0440\u0438\u044f \u0434\u043e\u043b\u0433\u043e\u0441\u0440\u043e\u0447\u043d\u043e\u0439 \u043f\u043e\u0434\u0434\u0435\u0440\u0436\u043a\u0438", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "\u0414\u043e\u043b\u0433\u043e\u0441\u0440\u043e\u0447\u043d\u043e\u0435 \u0430\u0440\u0445\u0438\u0432\u043d\u043e\u0435 \u0445\u0440\u0430\u043d\u0435\u043d\u0438\u0435", "point_of_view": "\u041a\u0440\u0443\u043f\u043d\u044b\u0439 \u0430\u0440\u0445\u0438\u0432, \u0432\u044b\u0431\u0438\u0440\u0430\u044e\u0449\u0438\u0439 \u0444\u043e\u0440\u043c\u0430\u0442 \u0434\u043b\u044f \u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u0446\u0438\u0444\u0440\u043e\u0432\u044b\u0445 \u043a\u043e\u043f\u0438\u0439 \u0438\u0441\u0442\u043e\u0440\u0438\u0447\u0435\u0441\u043a\u0438\u0445 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u043e\u0432 \u043d\u0430 100 \u043b\u0435\u0442 \u0441 \u0430\u043a\u0446\u0435\u043d\u0442\u043e\u043c \u043d\u0430 \u0434\u043e\u043b\u0433\u043e\u0432\u0435\u0447\u043d\u043e\u0441\u0442\u044c \u0438 \u043d\u0435\u0437\u0430\u0432\u0438\u0441\u0438\u043c\u043e\u0441\u0442\u044c \u043e\u0442 \u043f\u0440\u043e\u043f\u0440\u0438\u0435\u0442\u0430\u0440\u043d\u043e\u0433\u043e \u041f\u041e", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.452e97392afb3212f14b629caebc5d50"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
PDF
## Concept B
TIFF
## Aspect name
Долговечность и стабильность формата
## Aspect features
- Стандартизация
- Сложность формата
- История долгосрочной поддерж ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.452e97392afb3212f14b629caebc5d50
other_notes: С точки зрения долгосрочного архивного хранения (100 лет) с акцентом на долговечность и независимость от проприетарного ПО, формат PDF (особенно подмножества PDF/A) демонстрирует явные преимущества перед TIFF по всем заданным аспектным признакам. PDF/A является международным стандартом (ISO 19005) для долговременного архивного хранения, обладает более простой и интегрированной структурой (объединяет текст, шрифты, изображения и метаданные в одном файле), а его долгосрочная поддержка и экосистема открытых инструментов для проверки и рендеринга лучше соответствуют заданной перспективе. TIFF, хотя и широко используется в архивах, является более сложным и вариативным контейнерным форматом, что может создавать риски для будущей интерпретации, и его стандартизация менее жестко ориентирована именно на долговременное сохранение.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.a903b7c76fd4cc375d7ea4d0811bf2df
process:
{"a_concept": "PDF", "b_concept": "TIFF", "aspect_name": "\u041d\u0435\u0437\u0430\u0432\u0438\u0441\u0438\u043c\u043e\u0441\u0442\u044c \u043e\u0442 \u043f\u0440\u043e\u043f\u0440\u0438\u0435\u0442\u0430\u0440\u043d\u043e\u0433\u043e \u041f\u041e", "aspect_features": "- \u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u043e\u0442\u043a\u0440\u044b\u0442\u044b\u0445 \u0440\u0435\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u0439\n- \u0417\u0430\u0432\u0438\u0441\u0438\u043c\u043e\u0441\u0442\u044c \u043e\u0442 \u043a\u043e\u043d\u043a\u0440\u0435\u0442\u043d\u043e\u0433\u043e \u0432\u0435\u043d\u0434\u043e\u0440\u0430\n- \u041f\u0430\u0442\u0435\u043d\u0442\u043d\u044b\u0435 \u043e\u0433\u0440\u0430\u043d\u0438\u0447\u0435\u043d\u0438\u044f", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "\u0414\u043e\u043b\u0433\u043e\u0441\u0440\u043e\u0447\u043d\u043e\u0435 \u0430\u0440\u0445\u0438\u0432\u043d\u043e\u0435 \u0445\u0440\u0430\u043d\u0435\u043d\u0438\u0435", "point_of_view": "\u041a\u0440\u0443\u043f\u043d\u044b\u0439 \u0430\u0440\u0445\u0438\u0432, \u0432\u044b\u0431\u0438\u0440\u0430\u044e\u0449\u0438\u0439 \u0444\u043e\u0440\u043c\u0430\u0442 \u0434\u043b\u044f \u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u0446\u0438\u0444\u0440\u043e\u0432\u044b\u0445 \u043a\u043e\u043f\u0438\u0439 \u0438\u0441\u0442\u043e\u0440\u0438\u0447\u0435\u0441\u043a\u0438\u0445 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u043e\u0432 \u043d\u0430 100 \u043b\u0435\u0442 \u0441 \u0430\u043a\u0446\u0435\u043d\u0442\u043e\u043c \u043d\u0430 \u0434\u043e\u043b\u0433\u043e\u0432\u0435\u0447\u043d\u043e\u0441\u0442\u044c \u0438 \u043d\u0435\u0437\u0430\u0432\u0438\u0441\u0438\u043c\u043e\u0441\u0442\u044c \u043e\u0442 \u043f\u0440\u043e\u043f\u0440\u0438\u0435\u0442\u0430\u0440\u043d\u043e\u0433\u043e \u041f\u041e", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.a903b7c76fd4cc375d7ea4d0811bf2df"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
PDF
## Concept B
TIFF
## Aspect name
Независимость от проприетарного ПО
## Aspect features
- Наличие открытых реализаций
- Зависимость от конкретного вендора
-  ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.a903b7c76fd4cc375d7ea4d0811bf2df
other_notes: С точки зрения долгосрочного архивного хранения, формат PDF (особенно PDF/A) является стандартом ISO, разработанным специально для архивирования, с открытой спецификацией и широкой поддержкой открытого ПО. Формат TIFF, хотя и широко используется в архивах, исторически ассоциируется с проприетарными расширениями и в большей степени зависит от конкретных вендоров для поддержки всех функций. Оба формата имеют открытые реализации, но экосистема PDF в целом более открыта и стандартизирована для долгосрочного хранения.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.b1d510f1058b3ebeb98b90ab91d61e18
process:
{"a_concept": "PDF", "b_concept": "TIFF", "aspect_name": "\u0422\u0435\u0445\u043d\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0445\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0438 \u0434\u043b\u044f \u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0439", "aspect_features": "- \u041f\u043e\u0434\u0434\u0435\u0440\u0436\u043a\u0430 \u0433\u043b\u0443\u0431\u0438\u043d\u044b \u0446\u0432\u0435\u0442\u0430\n- \u041f\u043e\u0434\u0434\u0435\u0440\u0436\u043a\u0430 \u0441\u0436\u0430\u0442\u0438\u044f \u0431\u0435\u0437 \u043f\u043e\u0442\u0435\u0440\u044c\n- \u041c\u0435\u0442\u0430\u0434\u0430\u043d\u043d\u044b\u0435", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "\u0414\u043e\u043b\u0433\u043e\u0441\u0440\u043e\u0447\u043d\u043e\u0435 \u0430\u0440\u0445\u0438\u0432\u043d\u043e\u0435 \u0445\u0440\u0430\u043d\u0435\u043d\u0438\u0435", "point_of_view": "\u041a\u0440\u0443\u043f\u043d\u044b\u0439 \u0430\u0440\u0445\u0438\u0432, \u0432\u044b\u0431\u0438\u0440\u0430\u044e\u0449\u0438\u0439 \u0444\u043e\u0440\u043c\u0430\u0442 \u0434\u043b\u044f \u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u0446\u0438\u0444\u0440\u043e\u0432\u044b\u0445 \u043a\u043e\u043f\u0438\u0439 \u0438\u0441\u0442\u043e\u0440\u0438\u0447\u0435\u0441\u043a\u0438\u0445 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u043e\u0432 \u043d\u0430 100 \u043b\u0435\u0442 \u0441 \u0430\u043a\u0446\u0435\u043d\u0442\u043e\u043c \u043d\u0430 \u0434\u043e\u043b\u0433\u043e\u0432\u0435\u0447\u043d\u043e\u0441\u0442\u044c \u0438 \u043d\u0435\u0437\u0430\u0432\u0438\u0441\u0438\u043c\u043e\u0441\u0442\u044c \u043e\u0442 \u043f\u0440\u043e\u043f\u0440\u0438\u0435\u0442\u0430\u0440\u043d\u043e\u0433\u043e \u041f\u041e", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.b1d510f1058b3ebeb98b90ab91d61e18"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
PDF
## Concept B
TIFF
## Aspect name
Технические характеристики для хранения изображений
## Aspect features
- Поддержка глубины цвета
- Поддержка сжатия без пот ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.b1d510f1058b3ebeb98b90ab91d61e18
other_notes: С точки зрения долгосрочного архивного хранения (100 лет) для цифровых копий исторических документов, ключевыми дополнительными аспектами являются: открытость стандарта (PDF/A, основанный на открытых стандартах, предпочтительнее проприетарных расширений TIFF), самодостаточность (PDF может инкапсулировать шрифты, что важно для документов), а также широкое признание и долгосрочная поддержка. TIFF, хотя и является открытым стандартом, имеет множество вариантов, что может создать проблемы совместимости в будущем. PDF/A специально разработан для долгосрочного архивного хранения.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.c665fa80d8158531e36dc878ec906679
process:
{"a_concept": "PDF", "b_concept": "TIFF", "aspect_name": "\u0420\u0430\u0441\u043f\u0440\u043e\u0441\u0442\u0440\u0430\u043d\u0435\u043d\u043d\u043e\u0441\u0442\u044c \u0438 \u0441\u043e\u0432\u043c\u0435\u0441\u0442\u0438\u043c\u043e\u0441\u0442\u044c", "aspect_features": "- \u0428\u0438\u0440\u043e\u0442\u0430 \u043f\u043e\u0434\u0434\u0435\u0440\u0436\u043a\u0438 \u0432 \u041f\u041e\n- \u0412\u043e\u0437\u0440\u0430\u0441\u0442 \u0438 \u0437\u0440\u0435\u043b\u043e\u0441\u0442\u044c \u0444\u043e\u0440\u043c\u0430\u0442\u0430", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "\u0414\u043e\u043b\u0433\u043e\u0441\u0440\u043e\u0447\u043d\u043e\u0435 \u0430\u0440\u0445\u0438\u0432\u043d\u043e\u0435 \u0445\u0440\u0430\u043d\u0435\u043d\u0438\u0435", "point_of_view": "\u041a\u0440\u0443\u043f\u043d\u044b\u0439 \u0430\u0440\u0445\u0438\u0432, \u0432\u044b\u0431\u0438\u0440\u0430\u044e\u0449\u0438\u0439 \u0444\u043e\u0440\u043c\u0430\u0442 \u0434\u043b\u044f \u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u0446\u0438\u0444\u0440\u043e\u0432\u044b\u0445 \u043a\u043e\u043f\u0438\u0439 \u0438\u0441\u0442\u043e\u0440\u0438\u0447\u0435\u0441\u043a\u0438\u0445 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u043e\u0432 \u043d\u0430 100 \u043b\u0435\u0442 \u0441 \u0430\u043a\u0446\u0435\u043d\u0442\u043e\u043c \u043d\u0430 \u0434\u043e\u043b\u0433\u043e\u0432\u0435\u0447\u043d\u043e\u0441\u0442\u044c \u0438 \u043d\u0435\u0437\u0430\u0432\u0438\u0441\u0438\u043c\u043e\u0441\u0442\u044c \u043e\u0442 \u043f\u0440\u043e\u043f\u0440\u0438\u0435\u0442\u0430\u0440\u043d\u043e\u0433\u043e \u041f\u041e", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.c665fa80d8158531e36dc878ec906679"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
PDF
## Concept B
TIFF
## Aspect name
Распространенность и совместимость
## Aspect features
- Широта поддержки в ПО
- Возраст и зрелость формата
## Observer stra ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.c665fa80d8158531e36dc878ec906679
other_notes: С точки зрения долгосрочного архивного хранения для исторических документов, PDF (особенно PDF/A) часто считается более предпочтительным из-за его стандартизации, самодостаточности и встроенных метаданных. TIFF, хотя и является зрелым и широко поддерживаемым форматом для изображений, может требовать дополнительных файлов для метаданных и менее удобен для многостраничных документов. Ключевые дополнительные аспекты для рассмотрения: открытость стандарта, возможности сжатия без потерь, поддержка метаданных и пригодность для текстового поиска (OCR).
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.66704a4fe2beb456017e8f6c142573ba
process:

In [9]:
d02_total_dt

,result_name,result_value
0,comparison_winner,PDF
1,a_concept_score,47%
2,b_concept_score,-47%
3,LLM_model,deepseek/deepseek-chat
4,superordinate_concept,Raster image file format
5,perspective_observer_strategy,Долгосрочное архивное хранение
6,point_of_view,"Крупный архив, выбирающий формат для хранения ..."
7,observer_context_description,"Крупная организация (архив) должна выбрать, ка..."
8,a_concept,PDF
9,b_concept,TIFF

In [10]:
d02_aspect_dt

,type,aspect,feature,a_concept_winner,a_concept_score,b_concept_winner,b_concept_score
0,feature_score,Долговечность и стабильность формата,Стандартизация,True,8%,False,-
1,feature_score,Долговечность и стабильность формата,Сложность формата,True,8%,False,-
2,feature_score,Долговечность и стабильность формата,История долгосрочной поддержки,True,7%,False,-
3,feature_score,Независимость от проприетарного ПО,Наличие открытых реализаций,True,8%,False,-
4,feature_score,Независимость от проприетарного ПО,Зависимость от конкретного вендора,True,8%,False,-
5,feature_score,Независимость от проприетарного ПО,Патентные ограничения,True,7%,False,-
6,feature_score,Технические характеристики для хранения изобра...,Поддержка глубины цвета,False,-,True,7%
7,feature_score,Технические характеристики для хранения изобра...,Поддержка сжатия без потерь,False,-,False,-
8,feature_score,Технические характеристики для хранения изобра...,Метаданные,True,6%,False,-
9,feature_score,Распространенность и совместимость,Широта поддержки в ПО,True,10%,False,-
10,feature_score,Распространенность и совместимость,Возраст и зрелость формата,False,-,True,8%
11,feature_score,Эффективность хранения,Коэффициент сжатия,True,9%,False,-
12,feature_score,Эффективность хранения,Вычислительная сложность декодирования,False,-,True,7%

## Пример №3: Выбор лучшей стратегии для снижения углеродных выбросов в крупном&nbsp;городе

In [11]:
d03_observer_context_description = 'Мэрия города с населением 1 миллион человек должна выбрать, какой из двух проектов быстрее и эффективнее снизит выбросы CO2 на 15% в течение 5 лет.'
d03_a_concept = 'Масштабное субсидирование перехода на электромобили'
d03_b_concept = 'Модернизация и электрификация общественного транспорта'
d03_result = await calc_concept_aspect_comparison(d03_observer_context_description, d03_a_concept, d03_b_concept, frame_of_reference, output_content_language, extra_information_retrieval_strategy)
(d03_total_dt, d03_aspect_dt) = create_output_tables(d03_result, d03_observer_context_description, d03_a_concept, d03_b_concept)

start: input_id=superordinate_concept_identification_af.1.7c4b139220d16dcec6ab5e8be56c4348.0b3d2777d2008ccc87bdd4d1d42101f2
process:
{"concepts": "- \u041c\u0430\u0441\u0448\u0442\u0430\u0431\u043d\u043e\u0435 \u0441\u0443\u0431\u0441\u0438\u0434\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u0435\u0440\u0435\u0445\u043e\u0434\u0430 \u043d\u0430 \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043c\u043e\u0431\u0438\u043b\u0438\n- \u041c\u043e\u0434\u0435\u0440\u043d\u0438\u0437\u0430\u0446\u0438\u044f \u0438 \u044d\u043b\u0435\u043a\u0442\u0440\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u044f \u043e\u0431\u0449\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0433\u043e \u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u0430", "context_knowledge_specification": "### Context description\n\u041c\u044d\u0440\u0438\u044f \u0433\u043e\u0440\u043e\u0434\u0430 \u0441 \u043d\u0430\u0441\u0435\u043b\u0435\u043d\u0438\u0435\u043c 1 \u043c\u0438\u043b\u043b\u0438\u043e\u043d \u0447\u0435\u043b\u043e\u0432\u0435\u043a \u0434\u043e\u043b\u0436\u043d\u0430 \u0432\u044b\u0431\u0440\u0430\u0442\u044c, \u043a\u0430\u043a\u043e\u0439 \u0438\u0437 \u0434\u0432\u0443\u0445 \u043f\u0440\u043e\u0435\u043a\u0442\u043e\u0432 \u0431\u044b\u0441\u0442\u0440\u0435\u0435 \u0438 \u044d\u0444\u0444\u0435\u043a\u0442\u0438\u0432\u043d\u0435\u0435 \u0441\u043d\u0438\u0437\u0438\u0442 \u0432\u044b\u0431\u0440\u043e\u0441\u044b CO2 \u043d\u0430 15% \u0432 \u0442\u0435\u0447\u0435\u043d\u0438\u0435 5 \u043b\u0435\u0442.", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "superordinate_concept_identification_af", "input_id": "superordinate_concept_identification_af.1.7c4b139220d16dcec6ab5e8be56c4348.0b3d2777d2008ccc87bdd4d1d42101f2"}
end: input_id=superordinate_concept_identification_af.1.7c4b139220d16dcec6ab5e8be56c4348.0b3d2777d2008ccc87bdd4d1d42101f2
other_notes: Оба предложенных концепта являются конкретными проектами, направленными на снижение выбросов CO2 через преобразование транспортной системы города. Их общая цель в заданном контексте — сокращение выбросов, а общая сфера применения — транспортный сектор. Более широкие понятия, такие как 'экологическая политика' или 'устойчивое развитие', являются слишком общими и не отражают специфику транспортных мер, описанных в концептах.
start: input_id=perspective_features_af.1.7c4b139220d16dcec6ab5e8be56c4348.71a3b2dc0e607f0437b6588caadbbd0f
process:
{"concept": "\u041c\u0435\u0440\u044b \u043f\u043e \u0441\u043e\u043a\u0440\u0430\u0449\u0435\u043d\u0438\u044e \u0432\u044b\u0431\u0440\u043e\u0441\u043e\u0432 CO2 \u0432 \u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u043d\u043e\u043c \u0441\u0435\u043a\u0442\u043e\u0440\u0435", "observer_context_description": "\u041c\u044d\u0440\u0438\u044f \u0433\u043e\u0440\u043e\u0434\u0430 \u0441 \u043d\u0430\u0441\u0435\u043b\u0435\u043d\u0438\u0435\u043c 1 \u043c\u0438\u043b\u043b\u0438\u043e\u043d \u0447\u0435\u043b\u043e\u0432\u0435\u043a \u0434\u043e\u043b\u0436\u043d\u0430 \u0432\u044b\u0431\u0440\u0430\u0442\u044c, \u043a\u0430\u043a\u043e\u0439 \u0438\u0437 \u0434\u0432\u0443\u0445 \u043f\u0440\u043e\u0435\u043a\u0442\u043e\u0432 \u0431\u044b\u0441\u0442\u0440\u0435\u0435 \u0438 \u044d\u0444\u0444\u0435\u043a\u0442\u0438\u0432\u043d\u0435\u0435 \u0441\u043d\u0438\u0437\u0438\u0442 \u0432\u044b\u0431\u0440\u043e\u0441\u044b CO2 \u043d\u0430 15% \u0432 \u0442\u0435\u0447\u0435\u043d\u0438\u0435 5 \u043b\u0435\u0442.", "frame_of_reference": "Unbiased logic framework", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_features_af", "input_id": "perspective_features_af.1.7c4b139220d16dcec6ab5e8be56c4348.71a3b2dc0e607f0437b6588caadbbd0f"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to retrieve perspective aspects for a given Concept and specified perspective frame of reference, perspective observer strategy and point of view.
Identify the perspective observer strategy and the point of view from a given observer context description.
## Concept
Меры по сокращению выбросов CO2 в транспортн ...

end: input_id=perspective_features_af.1.7c4b139220d16dcec6ab5e8be56c4348.71a3b2dc0e607f0437b6588caadbbd0f
other_notes: Аспекты и их важность определены исходя из задачи выбора проекта для мэрии города с конкретной целью (снижение на 15% за 5 лет) в рамках объективной логической рамки. Аспекты 'Скорость' и 'Эффективность' имеют наивысший приоритет, так как прямо соответствуют критериям 'быстрее и эффективнее' из описания контекста наблюдателя. Оценки важности аспектов и признаков относительны внутри данного набора и определены данной перспективой.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.68ad89336f18632294d8347517497fc0
process:
{"a_concept": "\u041c\u0430\u0441\u0448\u0442\u0430\u0431\u043d\u043e\u0435 \u0441\u0443\u0431\u0441\u0438\u0434\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u0435\u0440\u0435\u0445\u043e\u0434\u0430 \u043d\u0430 \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043c\u043e\u0431\u0438\u043b\u0438", "b_concept": "\u041c\u043e\u0434\u0435\u0440\u043d\u0438\u0437\u0430\u0446\u0438\u044f \u0438 \u044d\u043b\u0435\u043a\u0442\u0440\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u044f \u043e\u0431\u0449\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0433\u043e \u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u0430", "aspect_name": "\u0421\u043a\u043e\u0440\u043e\u0441\u0442\u044c \u0434\u043e\u0441\u0442\u0438\u0436\u0435\u043d\u0438\u044f \u0446\u0435\u043b\u0435\u0432\u043e\u0433\u043e \u0441\u043d\u0438\u0436\u0435\u043d\u0438\u044f \u0432\u044b\u0431\u0440\u043e\u0441\u043e\u0432", "aspect_features": "- \u0412\u0440\u0435\u043c\u044f \u0434\u043e \u0434\u043e\u0441\u0442\u0438\u0436\u0435\u043d\u0438\u044f 15% \u0441\u043d\u0438\u0436\u0435\u043d\u0438\u044f\n- \u0414\u0438\u043d\u0430\u043c\u0438\u043a\u0430 \u0441\u043d\u0438\u0436\u0435\u043d\u0438\u044f \u0432\u044b\u0431\u0440\u043e\u0441\u043e\u0432 \u043f\u043e \u0433\u043e\u0434\u0430\u043c", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "\u0421\u0442\u0440\u0430\u0442\u0435\u0433\u0438\u044f \u043f\u0440\u0438\u043d\u044f\u0442\u0438\u044f \u0440\u0435\u0448\u0435\u043d\u0438\u0439 \u043d\u0430 \u043e\u0441\u043d\u043e\u0432\u0435 \u0441\u0440\u0430\u0432\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0433\u043e \u0430\u043d\u0430\u043b\u0438\u0437\u0430 \u044d\u0444\u0444\u0435\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u0438 \u0438 \u0441\u043a\u043e\u0440\u043e\u0441\u0442\u0438", "point_of_view": "\u0422\u043e\u0447\u043a\u0430 \u0437\u0440\u0435\u043d\u0438\u044f \u043c\u0443\u043d\u0438\u0446\u0438\u043f\u0430\u043b\u044c\u043d\u043e\u0433\u043e \u043e\u0440\u0433\u0430\u043d\u0430 \u0432\u043b\u0430\u0441\u0442\u0438, \u043e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0433\u043e \u0437\u0430 \u0434\u043e\u0441\u0442\u0438\u0436\u0435\u043d\u0438\u0435 \u043a\u043e\u043d\u043a\u0440\u0435\u0442\u043d\u043e\u0439 \u044d\u043a\u043e\u043b\u043e\u0433\u0438\u0447\u0435\u0441\u043a\u043e\u0439 \u0446\u0435\u043b\u0438 \u0432 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043d\u044b\u0435 \u0441\u0440\u043e\u043a\u0438", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.68ad89336f18632294d8347517497fc0"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
Масштабное субсидирование перехода на электромобили
## Concept B
Модернизация и электрификация общественного транспорта
## Aspect name
Скорость достижения целев ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.68ad89336f18632294d8347517497fc0
other_notes: Сравнение основано на логическом анализе в рамках заданной точки зрения. Модернизация общественного транспорта (Концепция B) позволяет централизованно и быстро обновить парк, что приводит к более быстрому и предсказуемому снижению выбросов на уровне города. Субсидирование электромобилей (Концепция A) зависит от индивидуальных решений граждан, что растягивает процесс замены парка и делает динамику снижения менее управляемой и более медленной для достижения конкретных муниципальных целей в установленные сроки.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.d54ecb513c7ed1d112a490a09450be6d
process:
{"a_concept": "\u041c\u0430\u0441\u0448\u0442\u0430\u0431\u043d\u043e\u0435 \u0441\u0443\u0431\u0441\u0438\u0434\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u0435\u0440\u0435\u0445\u043e\u0434\u0430 \u043d\u0430 \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043c\u043e\u0431\u0438\u043b\u0438", "b_concept": "\u041c\u043e\u0434\u0435\u0440\u043d\u0438\u0437\u0430\u0446\u0438\u044f \u0438 \u044d\u043b\u0435\u043a\u0442\u0440\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u044f \u043e\u0431\u0449\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0433\u043e \u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u0430", "aspect_name": "\u042d\u0444\u0444\u0435\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c \u043c\u0435\u0440 (\u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442 \u043d\u0430 \u0435\u0434\u0438\u043d\u0438\u0446\u0443 \u0437\u0430\u0442\u0440\u0430\u0442)", "aspect_features": "- \u0421\u043d\u0438\u0436\u0435\u043d\u0438\u0435 \u0432\u044b\u0431\u0440\u043e\u0441\u043e\u0432 CO2 \u043d\u0430 \u0435\u0434\u0438\u043d\u0438\u0446\u0443 \u0431\u044e\u0434\u0436\u0435\u0442\u043d\u044b\u0445 \u0437\u0430\u0442\u0440\u0430\u0442\n- \u041e\u0431\u0449\u0438\u0435 \u043a\u0430\u043f\u0438\u0442\u0430\u043b\u044c\u043d\u044b\u0435 \u0437\u0430\u0442\u0440\u0430\u0442\u044b\n- \u042d\u043a\u0441\u043f\u043b\u0443\u0430\u0442\u0430\u0446\u0438\u043e\u043d\u043d\u044b\u0435 \u0440\u0430\u0441\u0445\u043e\u0434\u044b", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "\u0421\u0442\u0440\u0430\u0442\u0435\u0433\u0438\u044f \u043f\u0440\u0438\u043d\u044f\u0442\u0438\u044f \u0440\u0435\u0448\u0435\u043d\u0438\u0439 \u043d\u0430 \u043e\u0441\u043d\u043e\u0432\u0435 \u0441\u0440\u0430\u0432\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0433\u043e \u0430\u043d\u0430\u043b\u0438\u0437\u0430 \u044d\u0444\u0444\u0435\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u0438 \u0438 \u0441\u043a\u043e\u0440\u043e\u0441\u0442\u0438", "point_of_view": "\u0422\u043e\u0447\u043a\u0430 \u0437\u0440\u0435\u043d\u0438\u044f \u043c\u0443\u043d\u0438\u0446\u0438\u043f\u0430\u043b\u044c\u043d\u043e\u0433\u043e \u043e\u0440\u0433\u0430\u043d\u0430 \u0432\u043b\u0430\u0441\u0442\u0438, \u043e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0433\u043e \u0437\u0430 \u0434\u043e\u0441\u0442\u0438\u0436\u0435\u043d\u0438\u0435 \u043a\u043e\u043d\u043a\u0440\u0435\u0442\u043d\u043e\u0439 \u044d\u043a\u043e\u043b\u043e\u0433\u0438\u0447\u0435\u0441\u043a\u043e\u0439 \u0446\u0435\u043b\u0438 \u0432 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043d\u044b\u0435 \u0441\u0440\u043e\u043a\u0438", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.d54ecb513c7ed1d112a490a09450be6d"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
Масштабное субсидирование перехода на электромобили
## Concept B
Модернизация и электрификация общественного транспорта
## Aspect name
Эффективность мер (резуль ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.d54ecb513c7ed1d112a490a09450be6d
other_notes: Сравнение проведено в рамках логической модели, основанной на общедоступных данных и принципах экономики транспорта. Модернизация общественного транспорта, как правило, демонстрирует более высокую совокупную эффективность для муниципалитета с точки зрения затрат на единицу снижения выбросов, благодаря централизации инвестиций и более высокому пассажиропотоку на одно транспортное средство. Субсидирование частных электромобилей распределяет затраты, но может привести к меньшему общему экологическому эффекту на вложенный бюджет и требует значительных сопутствующих инвестиций в инфраструктуру.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.35ea48eec556d75de1e36183f4f6d08e
process:
{"a_concept": "\u041c\u0430\u0441\u0448\u0442\u0430\u0431\u043d\u043e\u0435 \u0441\u0443\u0431\u0441\u0438\u0434\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u0435\u0440\u0435\u0445\u043e\u0434\u0430 \u043d\u0430 \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043c\u043e\u0431\u0438\u043b\u0438", "b_concept": "\u041c\u043e\u0434\u0435\u0440\u043d\u0438\u0437\u0430\u0446\u0438\u044f \u0438 \u044d\u043b\u0435\u043a\u0442\u0440\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u044f \u043e\u0431\u0449\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0433\u043e \u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u0430", "aspect_name": "\u041c\u0430\u0441\u0448\u0442\u0430\u0431 \u0432\u043e\u0437\u0434\u0435\u0439\u0441\u0442\u0432\u0438\u044f \u0438 \u043e\u0445\u0432\u0430\u0442", "aspect_features": "- \u0414\u043e\u043b\u044f \u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u043d\u043e\u0433\u043e \u0441\u0435\u043a\u0442\u043e\u0440\u0430 \u0433\u043e\u0440\u043e\u0434\u0430, \u043d\u0430 \u043a\u043e\u0442\u043e\u0440\u0443\u044e \u0432\u043b\u0438\u044f\u044e\u0442 \u043c\u0435\u0440\u044b\n- \u0410\u0431\u0441\u043e\u043b\u044e\u0442\u043d\u043e\u0435 \u0441\u043d\u0438\u0436\u0435\u043d\u0438\u0435 \u0432\u044b\u0431\u0440\u043e\u0441\u043e\u0432 CO2", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "\u0421\u0442\u0440\u0430\u0442\u0435\u0433\u0438\u044f \u043f\u0440\u0438\u043d\u044f\u0442\u0438\u044f \u0440\u0435\u0448\u0435\u043d\u0438\u0439 \u043d\u0430 \u043e\u0441\u043d\u043e\u0432\u0435 \u0441\u0440\u0430\u0432\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0433\u043e \u0430\u043d\u0430\u043b\u0438\u0437\u0430 \u044d\u0444\u0444\u0435\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u0438 \u0438 \u0441\u043a\u043e\u0440\u043e\u0441\u0442\u0438", "point_of_view": "\u0422\u043e\u0447\u043a\u0430 \u0437\u0440\u0435\u043d\u0438\u044f \u043c\u0443\u043d\u0438\u0446\u0438\u043f\u0430\u043b\u044c\u043d\u043e\u0433\u043e \u043e\u0440\u0433\u0430\u043d\u0430 \u0432\u043b\u0430\u0441\u0442\u0438, \u043e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0433\u043e \u0437\u0430 \u0434\u043e\u0441\u0442\u0438\u0436\u0435\u043d\u0438\u0435 \u043a\u043e\u043d\u043a\u0440\u0435\u0442\u043d\u043e\u0439 \u044d\u043a\u043e\u043b\u043e\u0433\u0438\u0447\u0435\u0441\u043a\u043e\u0439 \u0446\u0435\u043b\u0438 \u0432 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043d\u044b\u0435 \u0441\u0440\u043e\u043a\u0438", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.35ea48eec556d75de1e36183f4f6d08e"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
Масштабное субсидирование перехода на электромобили
## Concept B
Модернизация и электрификация общественного транспорта
## Aspect name
Масштаб воздействия и охв ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.35ea48eec556d75de1e36183f4f6d08e
other_notes: С точки зрения муниципального органа, стремящегося к быстрому достижению экологических целей, модернизация общественного транспорта (Концепция B) обеспечивает более прямое и быстрое воздействие на значительную долю городского транспорта и, как следствие, на абсолютное снижение выбросов. Субсидирование электромобилей (Концепция A) имеет более длительный и менее предсказуемый эффект, зависящий от индивидуальных решений граждан.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.6a3ef3aa6ee0ee5f451fa0f5a9c60d2c
process:

In [12]:
d03_total_dt

,result_name,result_value
0,comparison_winner,Модернизация и электрификация общественного тр...
1,a_concept_score,-93%
2,b_concept_score,93%
3,LLM_model,deepseek/deepseek-chat
4,superordinate_concept,Меры по сокращению выбросов CO2 в транспортном...
5,perspective_observer_strategy,Стратегия принятия решений на основе сравнител...
6,point_of_view,"Точка зрения муниципального органа власти, отв..."
7,observer_context_description,Мэрия города с населением 1 миллион человек до...
8,a_concept,Масштабное субсидирование перехода на электром...
9,b_concept,Модернизация и электрификация общественного тр...

In [13]:
d03_aspect_dt

,type,aspect,feature,a_concept_winner,a_concept_score,b_concept_winner,b_concept_score
0,feature_score,Скорость достижения целевого снижения выбросов,Время до достижения 15% снижения,False,-,True,12%
1,feature_score,Скорость достижения целевого снижения выбросов,Динамика снижения выбросов по годам,False,-,True,9%
2,feature_score,Эффективность мер (результат на единицу затрат),Снижение выбросов CO2 на единицу бюджетных затрат,False,-,True,8%
3,feature_score,Эффективность мер (результат на единицу затрат),Общие капитальные затраты,False,-,True,6%
4,feature_score,Эффективность мер (результат на единицу затрат),Эксплуатационные расходы,False,-,True,5%
5,feature_score,Масштаб воздействия и охват,"Доля транспортного сектора города, на которую ...",False,-,True,8%
6,feature_score,Масштаб воздействия и охват,Абсолютное снижение выбросов CO2,False,-,True,9%
7,feature_score,Технологическая готовность и реализуемость,Уровень технологической готовности (TRL),False,-,True,5%
8,feature_score,Технологическая готовность и реализуемость,Наличие необходимой инфраструктуры,False,-,True,4%
9,feature_score,Технологическая готовность и реализуемость,Сроки развертывания и внедрения,False,-,True,6%
10,feature_score,Социально-экономические последствия,Влияние на транспортную доступность для населения,False,-,True,5%
11,feature_score,Социально-экономические последствия,Влияние на местную экономику и бизнес,False,-,True,4%
12,feature_score,Социально-экономические последствия,Приемлемость для населения,True,4%,False,-
13,feature_score,Надежность и устойчивость результата,Долгосрочность эффекта после 5 лет,False,-,True,5%
14,feature_score,Надежность и устойчивость результата,Зависимость от внешних факторов (цены на топли...,False,-,True,5%
15,feature_score,Надежность и устойчивость результата,Надежность технологических решений,False,-,True,5%

## Пример №4. Выбор антисептика для бытовой обработки небольшой раны у ребёнка

In [14]:
d04_observer_context_description = 'Выбор антисептика для бытовой обработки небольшой раны у ребёнка (дома, без аллергий): кухонный порез, нужно убить бактерии и не повредить заживление'
d04_a_concept = 'изопропиловый спирт (70%)'
d04_b_concept = 'раствор хлоргексидина'
d04_result = await calc_concept_aspect_comparison(d04_observer_context_description, d04_a_concept, d04_b_concept, frame_of_reference, output_content_language, extra_information_retrieval_strategy)
(d04_total_dt, d04_aspect_dt) = create_output_tables(d04_result, d04_observer_context_description, d04_a_concept, d04_b_concept)

start: input_id=superordinate_concept_identification_af.1.7c4b139220d16dcec6ab5e8be56c4348.6aee9b62acbe5bbc2b6a22ce3001d195
process:
{"concepts": "- \u0438\u0437\u043e\u043f\u0440\u043e\u043f\u0438\u043b\u043e\u0432\u044b\u0439 \u0441\u043f\u0438\u0440\u0442 (70%)\n- \u0440\u0430\u0441\u0442\u0432\u043e\u0440 \u0445\u043b\u043e\u0440\u0433\u0435\u043a\u0441\u0438\u0434\u0438\u043d\u0430", "context_knowledge_specification": "### Context description\n\u0412\u044b\u0431\u043e\u0440 \u0430\u043d\u0442\u0438\u0441\u0435\u043f\u0442\u0438\u043a\u0430 \u0434\u043b\u044f \u0431\u044b\u0442\u043e\u0432\u043e\u0439 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0438 \u043d\u0435\u0431\u043e\u043b\u044c\u0448\u043e\u0439 \u0440\u0430\u043d\u044b \u0443 \u0440\u0435\u0431\u0451\u043d\u043a\u0430 (\u0434\u043e\u043c\u0430, \u0431\u0435\u0437 \u0430\u043b\u043b\u0435\u0440\u0433\u0438\u0439): \u043a\u0443\u0445\u043e\u043d\u043d\u044b\u0439 \u043f\u043e\u0440\u0435\u0437, \u043d\u0443\u0436\u043d\u043e \u0443\u0431\u0438\u0442\u044c \u0431\u0430\u043a\u0442\u0435\u0440\u0438\u0438 \u0438 \u043d\u0435 \u043f\u043e\u0432\u0440\u0435\u0434\u0438\u0442\u044c \u0437\u0430\u0436\u0438\u0432\u043b\u0435\u043d\u0438\u0435", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "superordinate_concept_identification_af", "input_id": "superordinate_concept_identification_af.1.7c4b139220d16dcec6ab5e8be56c4348.6aee9b62acbe5bbc2b6a22ce3001d195"}
end: input_id=superordinate_concept_identification_af.1.7c4b139220d16dcec6ab5e8be56c4348.6aee9b62acbe5bbc2b6a22ce3001d195
other_notes: Оба вещества являются антисептиками, но более узкие категории (например, 'спиртовой антисептик' или 'антисептик на основе бигуанида') не охватывают оба понятия. 'Антисептик для обработки кожи' является наименее общим суперординатным понятием, которое точно описывает оба данных средства в контексте бытовой обработки небольших ран.
start: input_id=perspective_features_af.1.7c4b139220d16dcec6ab5e8be56c4348.0745c9e1a124ef384107be78f9b5273f
process:
{"concept": "\u0430\u043d\u0442\u0438\u0441\u0435\u043f\u0442\u0438\u043a \u0434\u043b\u044f \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0438 \u043a\u043e\u0436\u0438", "observer_context_description": "\u0412\u044b\u0431\u043e\u0440 \u0430\u043d\u0442\u0438\u0441\u0435\u043f\u0442\u0438\u043a\u0430 \u0434\u043b\u044f \u0431\u044b\u0442\u043e\u0432\u043e\u0439 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0438 \u043d\u0435\u0431\u043e\u043b\u044c\u0448\u043e\u0439 \u0440\u0430\u043d\u044b \u0443 \u0440\u0435\u0431\u0451\u043d\u043a\u0430 (\u0434\u043e\u043c\u0430, \u0431\u0435\u0437 \u0430\u043b\u043b\u0435\u0440\u0433\u0438\u0439): \u043a\u0443\u0445\u043e\u043d\u043d\u044b\u0439 \u043f\u043e\u0440\u0435\u0437, \u043d\u0443\u0436\u043d\u043e \u0443\u0431\u0438\u0442\u044c \u0431\u0430\u043a\u0442\u0435\u0440\u0438\u0438 \u0438 \u043d\u0435 \u043f\u043e\u0432\u0440\u0435\u0434\u0438\u0442\u044c \u0437\u0430\u0436\u0438\u0432\u043b\u0435\u043d\u0438\u0435", "frame_of_reference": "Unbiased logic framework", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_features_af", "input_id": "perspective_features_af.1.7c4b139220d16dcec6ab5e8be56c4348.0745c9e1a124ef384107be78f9b5273f"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to retrieve perspective aspects for a given Concept and specified perspective frame of reference, perspective observer strategy and point of view.
Identify the perspective observer strategy and the point of view from a given observer context description.
## Concept
антисептик для обработки кожи
## Observer co ...

end: input_id=perspective_features_af.1.7c4b139220d16dcec6ab5e8be56c4348.0745c9e1a124ef384107be78f9b5273f
other_notes: Аспекты и их важность определены исходя из задачи выбора средства для бытовой обработки небольшой раны у ребёнка. Приоритет отдан безопасности и эффективности. Особое внимание уделено отсутствию негативного влияния на процесс заживления, что прямо указано в контексте наблюдателя. Все аспекты рассматриваются в рамках объективной логики, основанной на медицинских фактах.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.4d1d2f7b4fef53c9736eff10b8350fe3
process:
{"a_concept": "\u0438\u0437\u043e\u043f\u0440\u043e\u043f\u0438\u043b\u043e\u0432\u044b\u0439 \u0441\u043f\u0438\u0440\u0442 (70%)", "b_concept": "\u0440\u0430\u0441\u0442\u0432\u043e\u0440 \u0445\u043b\u043e\u0440\u0433\u0435\u043a\u0441\u0438\u0434\u0438\u043d\u0430", "aspect_name": "\u042d\u0444\u0444\u0435\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c \u043f\u0440\u043e\u0442\u0438\u0432\u043e\u043c\u0438\u043a\u0440\u043e\u0431\u043d\u043e\u0433\u043e \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u044f", "aspect_features": "- \u0421\u043f\u0435\u043a\u0442\u0440 \u0430\u043d\u0442\u0438\u043c\u0438\u043a\u0440\u043e\u0431\u043d\u043e\u0439 \u0430\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u0438\n- \u0421\u043a\u043e\u0440\u043e\u0441\u0442\u044c \u043d\u0430\u0441\u0442\u0443\u043f\u043b\u0435\u043d\u0438\u044f \u044d\u0444\u0444\u0435\u043a\u0442\u0430", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "\u0420\u0430\u0446\u0438\u043e\u043d\u0430\u043b\u044c\u043d\u044b\u0439 \u0432\u044b\u0431\u043e\u0440 \u043d\u0430 \u043e\u0441\u043d\u043e\u0432\u0435 \u043c\u0435\u0434\u0438\u0446\u0438\u043d\u0441\u043a\u0438\u0445 \u0444\u0430\u043a\u0442\u043e\u0432 \u0438 \u0431\u0435\u0437\u043e\u043f\u0430\u0441\u043d\u043e\u0441\u0442\u0438", "point_of_view": "\u0417\u0430\u0431\u043e\u0442\u043b\u0438\u0432\u044b\u0439 \u0440\u043e\u0434\u0438\u0442\u0435\u043b\u044c, \u0432\u044b\u0431\u0438\u0440\u0430\u044e\u0449\u0438\u0439 \u0441\u0440\u0435\u0434\u0441\u0442\u0432\u043e \u0434\u043b\u044f \u0431\u0435\u0437\u043e\u043f\u0430\u0441\u043d\u043e\u0439 \u0438 \u044d\u0444\u0444\u0435\u043a\u0442\u0438\u0432\u043d\u043e\u0439 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0438 \u043d\u0435\u0431\u043e\u043b\u044c\u0448\u043e\u0439 \u0440\u0430\u043d\u044b \u0443 \u0440\u0435\u0431\u0451\u043d\u043a\u0430 \u0432 \u0431\u044b\u0442\u043e\u0432\u044b\u0445 \u0443\u0441\u043b\u043e\u0432\u0438\u044f\u0445", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.4d1d2f7b4fef53c9736eff10b8350fe3"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
изопропиловый спирт (70%)
## Concept B
раствор хлоргексидина
## Aspect name
Эффективность противомикробного действия
## Aspect features
- Спектр антимикробной а ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.4d1d2f7b4fef53c9736eff10b8350fe3
other_notes: С точки зрения заботливого родителя, важны дополнительные аспекты: безопасность для ребёнка (хлоргексидин менее раздражает кожу и слизистые, чем спирт) и остаточный эффект (хлоргексидин обладает пролонгированным действием). В рамках рационального выбора на основе медицинских фактов, для обработки небольших ран у детей в быту раствор хлоргексидина часто считается более предпочтительным из-за более широкого спектра действия (включая некоторые вирусы и грибы), безопасности и остаточного эффекта, несмотря на более медленное начало действия по сравнению с изопропиловым спиртом.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.a0beba3f690fa33b8628d79be15e892b
process:
{"a_concept": "\u0438\u0437\u043e\u043f\u0440\u043e\u043f\u0438\u043b\u043e\u0432\u044b\u0439 \u0441\u043f\u0438\u0440\u0442 (70%)", "b_concept": "\u0440\u0430\u0441\u0442\u0432\u043e\u0440 \u0445\u043b\u043e\u0440\u0433\u0435\u043a\u0441\u0438\u0434\u0438\u043d\u0430", "aspect_name": "\u0411\u0435\u0437\u043e\u043f\u0430\u0441\u043d\u043e\u0441\u0442\u044c \u0434\u043b\u044f \u0434\u0435\u0442\u0441\u043a\u043e\u0439 \u043a\u043e\u0436\u0438 \u0438 \u0437\u0430\u0436\u0438\u0432\u043b\u0435\u043d\u0438\u044f", "aspect_features": "- \u041e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0438\u0435 \u043d\u0435\u0433\u0430\u0442\u0438\u0432\u043d\u043e\u0433\u043e \u0432\u043b\u0438\u044f\u043d\u0438\u044f \u043d\u0430 \u0440\u0435\u0433\u0435\u043d\u0435\u0440\u0430\u0446\u0438\u044e \u0442\u043a\u0430\u043d\u0435\u0439\n- \u041d\u0438\u0437\u043a\u0438\u0439 \u0440\u0438\u0441\u043a \u0440\u0430\u0437\u0434\u0440\u0430\u0436\u0435\u043d\u0438\u044f\n- \u041e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0438\u0435 \u0441\u0438\u0441\u0442\u0435\u043c\u043d\u043e\u0439 \u0442\u043e\u043a\u0441\u0438\u0447\u043d\u043e\u0441\u0442\u0438 \u043f\u0440\u0438 \u043c\u0435\u0441\u0442\u043d\u043e\u043c \u043f\u0440\u0438\u043c\u0435\u043d\u0435\u043d\u0438\u0438", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "\u0420\u0430\u0446\u0438\u043e\u043d\u0430\u043b\u044c\u043d\u044b\u0439 \u0432\u044b\u0431\u043e\u0440 \u043d\u0430 \u043e\u0441\u043d\u043e\u0432\u0435 \u043c\u0435\u0434\u0438\u0446\u0438\u043d\u0441\u043a\u0438\u0445 \u0444\u0430\u043a\u0442\u043e\u0432 \u0438 \u0431\u0435\u0437\u043e\u043f\u0430\u0441\u043d\u043e\u0441\u0442\u0438", "point_of_view": "\u0417\u0430\u0431\u043e\u0442\u043b\u0438\u0432\u044b\u0439 \u0440\u043e\u0434\u0438\u0442\u0435\u043b\u044c, \u0432\u044b\u0431\u0438\u0440\u0430\u044e\u0449\u0438\u0439 \u0441\u0440\u0435\u0434\u0441\u0442\u0432\u043e \u0434\u043b\u044f \u0431\u0435\u0437\u043e\u043f\u0430\u0441\u043d\u043e\u0439 \u0438 \u044d\u0444\u0444\u0435\u043a\u0442\u0438\u0432\u043d\u043e\u0439 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0438 \u043d\u0435\u0431\u043e\u043b\u044c\u0448\u043e\u0439 \u0440\u0430\u043d\u044b \u0443 \u0440\u0435\u0431\u0451\u043d\u043a\u0430 \u0432 \u0431\u044b\u0442\u043e\u0432\u044b\u0445 \u0443\u0441\u043b\u043e\u0432\u0438\u044f\u0445", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.a0beba3f690fa33b8628d79be15e892b"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
изопропиловый спирт (70%)
## Concept B
раствор хлоргексидина
## Aspect name
Безопасность для детской кожи и заживления
## Aspect features
- Отсутствие негативно ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.a0beba3f690fa33b8628d79be15e892b
other_notes: Сравнение основано на медицинских фактах. 70% изопропиловый спирт обладает выраженным подсушивающим и раздражающим действием, может повреждать грануляционную ткань и замедлять заживление, особенно у детей. Раствор хлоргексидина (обычно 0.05% водный) обладает широким антисептическим действием, не повреждает ткани, имеет низкий риск раздражения и системной абсорбции при местном применении на неповрежденной или поврежденной коже, что делает его предпочтительным для обработки небольших ран у детей в бытовых условиях.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.c2559275019193a4888f1e59d9e64ec0
process:
{"a_concept": "\u0438\u0437\u043e\u043f\u0440\u043e\u043f\u0438\u043b\u043e\u0432\u044b\u0439 \u0441\u043f\u0438\u0440\u0442 (70%)", "b_concept": "\u0440\u0430\u0441\u0442\u0432\u043e\u0440 \u0445\u043b\u043e\u0440\u0433\u0435\u043a\u0441\u0438\u0434\u0438\u043d\u0430", "aspect_name": "\u0423\u0434\u043e\u0431\u0441\u0442\u0432\u043e \u043f\u0440\u0438\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0432 \u0431\u044b\u0442\u0443", "aspect_features": "- \u0424\u043e\u0440\u043c\u0430 \u0432\u044b\u043f\u0443\u0441\u043a\u0430\n- \u041f\u0440\u043e\u0441\u0442\u043e\u0442\u0430 \u043d\u0430\u043d\u0435\u0441\u0435\u043d\u0438\u044f\n- \u041e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0438\u0435 \u0441\u0438\u043b\u044c\u043d\u043e\u0433\u043e \u043e\u043a\u0440\u0430\u0448\u0438\u0432\u0430\u043d\u0438\u044f \u043a\u043e\u0436\u0438", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "\u0420\u0430\u0446\u0438\u043e\u043d\u0430\u043b\u044c\u043d\u044b\u0439 \u0432\u044b\u0431\u043e\u0440 \u043d\u0430 \u043e\u0441\u043d\u043e\u0432\u0435 \u043c\u0435\u0434\u0438\u0446\u0438\u043d\u0441\u043a\u0438\u0445 \u0444\u0430\u043a\u0442\u043e\u0432 \u0438 \u0431\u0435\u0437\u043e\u043f\u0430\u0441\u043d\u043e\u0441\u0442\u0438", "point_of_view": "\u0417\u0430\u0431\u043e\u0442\u043b\u0438\u0432\u044b\u0439 \u0440\u043e\u0434\u0438\u0442\u0435\u043b\u044c, \u0432\u044b\u0431\u0438\u0440\u0430\u044e\u0449\u0438\u0439 \u0441\u0440\u0435\u0434\u0441\u0442\u0432\u043e \u0434\u043b\u044f \u0431\u0435\u0437\u043e\u043f\u0430\u0441\u043d\u043e\u0439 \u0438 \u044d\u0444\u0444\u0435\u043a\u0442\u0438\u0432\u043d\u043e\u0439 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0438 \u043d\u0435\u0431\u043e\u043b\u044c\u0448\u043e\u0439 \u0440\u0430\u043d\u044b \u0443 \u0440\u0435\u0431\u0451\u043d\u043a\u0430 \u0432 \u0431\u044b\u0442\u043e\u0432\u044b\u0445 \u0443\u0441\u043b\u043e\u0432\u0438\u044f\u0445", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.c2559275019193a4888f1e59d9e64ec0"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
изопропиловый спирт (70%)
## Concept B
раствор хлоргексидина
## Aspect name
Удобство применения в быту
## Aspect features
- Форма выпуска
- Простота нанесения
- ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.c2559275019193a4888f1e59d9e64ec0
other_notes: С точки зрения заботливого родителя, важны дополнительные аспекты: безопасность для детей (изопропиловый спирт может вызывать сильное жжение, хлоргексидин обычно мягче), эффективность противомикробного действия (хлоргексидин имеет пролонгированное действие) и риск проглатывания (оба требуют хранения в недоступном для детей месте). В рамках рационального выбора на основе медицинских фактов, для обработки небольших ран у детей в быту часто предпочтительнее раствор хлоргексидина из-за меньшей болезненности и пролонгированного действия, несмотря на возможное слабое окрашивание при использовании некоторых форм (например, с красителями). Изопропиловый спирт (70%) эффективен, но вызывает жжение и сушит кожу.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.2c96f56d415918b2d134b998c155884b
process:
{"a_concept": "\u0438\u0437\u043e\u043f\u0440\u043e\u043f\u0438\u043b\u043e\u0432\u044b\u0439 \u0441\u043f\u0438\u0440\u0442 (70%)", "b_concept": "\u0440\u0430\u0441\u0442\u0432\u043e\u0440 \u0445\u043b\u043e\u0440\u0433\u0435\u043a\u0441\u0438\u0434\u0438\u043d\u0430", "aspect_name": "\u0414\u043e\u0441\u0442\u0443\u043f\u043d\u043e\u0441\u0442\u044c \u0438 \u044d\u043a\u043e\u043d\u043e\u043c\u0438\u0447\u043d\u043e\u0441\u0442\u044c", "aspect_features": "- \u0426\u0435\u043d\u0430\n- \u0428\u0438\u0440\u043e\u0442\u0430 \u0440\u0430\u0441\u043f\u0440\u043e\u0441\u0442\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u0432 \u0430\u043f\u0442\u0435\u043a\u0430\u0445", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "\u0420\u0430\u0446\u0438\u043e\u043d\u0430\u043b\u044c\u043d\u044b\u0439 \u0432\u044b\u0431\u043e\u0440 \u043d\u0430 \u043e\u0441\u043d\u043e\u0432\u0435 \u043c\u0435\u0434\u0438\u0446\u0438\u043d\u0441\u043a\u0438\u0445 \u0444\u0430\u043a\u0442\u043e\u0432 \u0438 \u0431\u0435\u0437\u043e\u043f\u0430\u0441\u043d\u043e\u0441\u0442\u0438", "point_of_view": "\u0417\u0430\u0431\u043e\u0442\u043b\u0438\u0432\u044b\u0439 \u0440\u043e\u0434\u0438\u0442\u0435\u043b\u044c, \u0432\u044b\u0431\u0438\u0440\u0430\u044e\u0449\u0438\u0439 \u0441\u0440\u0435\u0434\u0441\u0442\u0432\u043e \u0434\u043b\u044f \u0431\u0435\u0437\u043e\u043f\u0430\u0441\u043d\u043e\u0439 \u0438 \u044d\u0444\u0444\u0435\u043a\u0442\u0438\u0432\u043d\u043e\u0439 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0438 \u043d\u0435\u0431\u043e\u043b\u044c\u0448\u043e\u0439 \u0440\u0430\u043d\u044b \u0443 \u0440\u0435\u0431\u0451\u043d\u043a\u0430 \u0432 \u0431\u044b\u0442\u043e\u0432\u044b\u0445 \u0443\u0441\u043b\u043e\u0432\u0438\u044f\u0445", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.2c96f56d415918b2d134b998c155884b"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
изопропиловый спирт (70%)
## Concept B
раствор хлоргексидина
## Aspect name
Доступность и экономичность
## Aspect features
- Цена
- Широта распространения в апт ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.2c96f56d415918b2d134b998c155884b
other_notes: С точки зрения доступности и экономичности, изопропиловый спирт (70%) обычно дешевле и более широко распространён в аптеках и магазинах, чем раствор хлоргексидина. Однако, при выборе средства для обработки раны у ребёнка с точки зрения заботливого родителя, рациональный выбор на основе медицинских фактов и безопасности может отдавать предпочтение хлоргексидину из-за его меньшей раздражающей способности и лучшей переносимости для детской кожи, что выходит за рамки заданного аспекта сравнения.

In [15]:
d04_total_dt

,result_name,result_value
0,comparison_winner,раствор хлоргексидина
1,a_concept_score,-9%
2,b_concept_score,9%
3,LLM_model,deepseek/deepseek-chat
4,superordinate_concept,антисептик для обработки кожи
5,perspective_observer_strategy,Рациональный выбор на основе медицинских факто...
6,point_of_view,"Заботливый родитель, выбирающий средство для б..."
7,observer_context_description,Выбор антисептика для бытовой обработки неболь...
8,a_concept,изопропиловый спирт (70%)
9,b_concept,раствор хлоргексидина

In [16]:
d04_aspect_dt

,type,aspect,feature,a_concept_winner,a_concept_score,b_concept_winner,b_concept_score
0,feature_score,Эффективность противомикробного действия,Спектр антимикробной активности,False,-,True,17%
1,feature_score,Эффективность противомикробного действия,Скорость наступления эффекта,True,13%,False,-
2,feature_score,Безопасность для детской кожи и заживления,Отсутствие негативного влияния на регенерацию ...,False,-,True,11%
3,feature_score,Безопасность для детской кожи и заживления,Низкий риск раздражения,False,-,True,10%
4,feature_score,Безопасность для детской кожи и заживления,Отсутствие системной токсичности при местном п...,False,-,True,10%
5,feature_score,Удобство применения в быту,Форма выпуска,False,-,False,-
6,feature_score,Удобство применения в быту,Простота нанесения,False,-,False,-
7,feature_score,Удобство применения в быту,Отсутствие сильного окрашивания кожи,True,6%,False,-
8,feature_score,Доступность и экономичность,Цена,True,10%,False,-
9,feature_score,Доступность и экономичность,Широта распространения в аптеках,True,8%,False,-

## Пример №5. Выбор смартфона для фрилансера-дизайнера

In [17]:
d05_observer_context_description = 'Работаю фрилансером-дизайнером, много времени провожу в Adobe Photoshop и Lightroom на мобильном, часто редактирую фото/видео на ходу, синхронизирую с MacBook, важна стабильность ПО и автономность батареи (день без подзарядки)'
d05_a_concept = 'Google Pixel 9 Pro'
d05_b_concept = 'iPhone 14 Pro'
d05_result = await calc_concept_aspect_comparison(d05_observer_context_description, d05_a_concept, d05_b_concept, frame_of_reference, output_content_language, extra_information_retrieval_strategy)
(d05_total_dt, d05_aspect_dt) = create_output_tables(d05_result, d05_observer_context_description, d05_a_concept, d05_b_concept)

start: input_id=superordinate_concept_identification_af.1.7c4b139220d16dcec6ab5e8be56c4348.568c87a3b31c9a2635b3337bc799fc1c
process:
{"concepts": "- Google Pixel 9 Pro\n- iPhone 14 Pro", "context_knowledge_specification": "### Context description\n\u0420\u0430\u0431\u043e\u0442\u0430\u044e \u0444\u0440\u0438\u043b\u0430\u043d\u0441\u0435\u0440\u043e\u043c-\u0434\u0438\u0437\u0430\u0439\u043d\u0435\u0440\u043e\u043c, \u043c\u043d\u043e\u0433\u043e \u0432\u0440\u0435\u043c\u0435\u043d\u0438 \u043f\u0440\u043e\u0432\u043e\u0436\u0443 \u0432 Adobe Photoshop \u0438 Lightroom \u043d\u0430 \u043c\u043e\u0431\u0438\u043b\u044c\u043d\u043e\u043c, \u0447\u0430\u0441\u0442\u043e \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u0443\u044e \u0444\u043e\u0442\u043e/\u0432\u0438\u0434\u0435\u043e \u043d\u0430 \u0445\u043e\u0434\u0443, \u0441\u0438\u043d\u0445\u0440\u043e\u043d\u0438\u0437\u0438\u0440\u0443\u044e \u0441 MacBook, \u0432\u0430\u0436\u043d\u0430 \u0441\u0442\u0430\u0431\u0438\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u041f\u041e \u0438 \u0430\u0432\u0442\u043e\u043d\u043e\u043c\u043d\u043e\u0441\u0442\u044c \u0431\u0430\u0442\u0430\u0440\u0435\u0438 (\u0434\u0435\u043d\u044c \u0431\u0435\u0437 \u043f\u043e\u0434\u0437\u0430\u0440\u044f\u0434\u043a\u0438)", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "superordinate_concept_identification_af", "input_id": "superordinate_concept_identification_af.1.7c4b139220d16dcec6ab5e8be56c4348.568c87a3b31c9a2635b3337bc799fc1c"}
end: input_id=superordinate_concept_identification_af.1.7c4b139220d16dcec6ab5e8be56c4348.568c87a3b31c9a2635b3337bc799fc1c
other_notes: The provided context describes a user who is a freelance designer, heavily reliant on mobile Adobe Photoshop and Lightroom for on-the-go photo/video editing, with a need for software stability and all-day battery life, and who syncs with a MacBook. While both the Google Pixel 9 Pro and iPhone 14 Pro are specific models of smartphones, the most precise and informative superordinate concept that captures their shared primary function and market position, especially relevant to the user's high-performance mobile computing needs, is 'flagship smartphones'. Broader terms like 'mobile devices' or 'electronics' are less specific and do not convey the high-end, performance-oriented nature implied by the context and the specific models listed.
start: input_id=perspective_features_af.1.7c4b139220d16dcec6ab5e8be56c4348.19fb7ef298bc2c3ad7261d41acec9af2
process:
{"concept": "flagship smartphones", "observer_context_description": "\u0420\u0430\u0431\u043e\u0442\u0430\u044e \u0444\u0440\u0438\u043b\u0430\u043d\u0441\u0435\u0440\u043e\u043c-\u0434\u0438\u0437\u0430\u0439\u043d\u0435\u0440\u043e\u043c, \u043c\u043d\u043e\u0433\u043e \u0432\u0440\u0435\u043c\u0435\u043d\u0438 \u043f\u0440\u043e\u0432\u043e\u0436\u0443 \u0432 Adobe Photoshop \u0438 Lightroom \u043d\u0430 \u043c\u043e\u0431\u0438\u043b\u044c\u043d\u043e\u043c, \u0447\u0430\u0441\u0442\u043e \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u0443\u044e \u0444\u043e\u0442\u043e/\u0432\u0438\u0434\u0435\u043e \u043d\u0430 \u0445\u043e\u0434\u0443, \u0441\u0438\u043d\u0445\u0440\u043e\u043d\u0438\u0437\u0438\u0440\u0443\u044e \u0441 MacBook, \u0432\u0430\u0436\u043d\u0430 \u0441\u0442\u0430\u0431\u0438\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u041f\u041e \u0438 \u0430\u0432\u0442\u043e\u043d\u043e\u043c\u043d\u043e\u0441\u0442\u044c \u0431\u0430\u0442\u0430\u0440\u0435\u0438 (\u0434\u0435\u043d\u044c \u0431\u0435\u0437 \u043f\u043e\u0434\u0437\u0430\u0440\u044f\u0434\u043a\u0438)", "frame_of_reference": "Unbiased logic framework", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_features_af", "input_id": "perspective_features_af.1.7c4b139220d16dcec6ab5e8be56c4348.19fb7ef298bc2c3ad7261d41acec9af2"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to retrieve perspective aspects for a given Concept and specified perspective frame of reference, perspective observer strategy and point of view.
Identify the perspective observer strategy and the point of view from a given observer context description.
## Concept
flagship smartphones
## Observer context des ...

end: input_id=perspective_features_af.1.7c4b139220d16dcec6ab5e8be56c4348.19fb7ef298bc2c3ad7261d41acec9af2
other_notes: Аспекты и их важность определены на основе описания контекста наблюдателя (фрилансер-дизайнер, использующий ресурсоемкие приложения, нуждающийся в стабильности и автономности). В рамках объективной логической системы оценки, аспекты, напрямую влияющие на продуктивность и выполнение рабочих задач (производительность, автономность), получили наивысшие баллы. Важность функций внутри аспектов также определена этой перспективой (например, стабильность ОС важнее объема ОЗУ, а время автономной работы важнее емкости батареи).
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.24370c1ad500f60a1745fdaadc4f4252
process:
{"a_concept": "Google Pixel 9 Pro", "b_concept": "iPhone 14 Pro", "aspect_name": "\u041f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u0438 \u0441\u0442\u0430\u0431\u0438\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u0441\u0438\u0441\u0442\u0435\u043c\u044b", "aspect_features": "- \u041f\u0440\u043e\u0446\u0435\u0441\u0441\u043e\u0440\n- \u041e\u043f\u0435\u0440\u0430\u0442\u0438\u0432\u043d\u0430\u044f \u043f\u0430\u043c\u044f\u0442\u044c (\u041e\u0417\u0423)\n- \u0421\u0442\u0430\u0431\u0438\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u043e\u043f\u0435\u0440\u0430\u0446\u0438\u043e\u043d\u043d\u043e\u0439 \u0441\u0438\u0441\u0442\u0435\u043c\u044b", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "\u041f\u0440\u0430\u0433\u043c\u0430\u0442\u0438\u0447\u043d\u044b\u0439 \u043f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u043e\u043d\u0430\u043b", "point_of_view": "\u041c\u043e\u0431\u0438\u043b\u044c\u043d\u044b\u0439 \u0434\u0438\u0437\u0430\u0439\u043d\u0435\u0440-\u0444\u0440\u0438\u043b\u0430\u043d\u0441\u0435\u0440, \u0437\u0430\u0432\u0438\u0441\u044f\u0449\u0438\u0439 \u043e\u0442 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438 \u0438 \u0430\u0432\u0442\u043e\u043d\u043e\u043c\u043d\u043e\u0441\u0442\u0438", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.24370c1ad500f60a1745fdaadc4f4252"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
Google Pixel 9 Pro
## Concept B
iPhone 14 Pro
## Aspect name
Производительность и стабильность системы
## Aspect features
- Процессор
- Оперативная память (ОЗУ) ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.24370c1ad500f60a1745fdaadc4f4252
other_notes: С точки зрения мобильного дизайнера-фрилансера, важны не только чистая производительность, но и стабильность при работе с требовательными приложениями (например, Figma, Adobe XD) и автономность. iPhone 14 Pro с процессором A16 Bionic и оптимизированной iOS часто демонстрирует более стабильную и предсказуемую производительность в долгосрочной перспективе, что критично для дедлайнов. Google Pixel 9 Pro с Tensor G4 и большим объемом ОЗУ (12 ГБ против 6 ГБ у iPhone 14 Pro) может лучше справляться с многозадачностью и удерживать больше приложений в памяти, но может уступать в абсолютной мощности CPU/GPU и долгосрочной стабильности обновлений. Автономность (хотя и не указана явно в аспектах) также важна для фрилансера; здесь оба устройства сильны, но оптимизация iOS может давать преимущество. В рамках объективной логической оценки, сравнение проводится по заявленным характеристикам и общепризнанным показателям производительности и стабильности.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.a1a341144c00be1328be6059d57bd123
process:
{"a_concept": "Google Pixel 9 Pro", "b_concept": "iPhone 14 Pro", "aspect_name": "\u0410\u0432\u0442\u043e\u043d\u043e\u043c\u043d\u043e\u0441\u0442\u044c", "aspect_features": "- \u0415\u043c\u043a\u043e\u0441\u0442\u044c \u0430\u043a\u043a\u0443\u043c\u0443\u043b\u044f\u0442\u043e\u0440\u0430\n- \u0412\u0440\u0435\u043c\u044f \u0430\u0432\u0442\u043e\u043d\u043e\u043c\u043d\u043e\u0439 \u0440\u0430\u0431\u043e\u0442\u044b \u043f\u0440\u0438 \u0430\u043a\u0442\u0438\u0432\u043d\u043e\u043c \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0438\n- \u041f\u043e\u0434\u0434\u0435\u0440\u0436\u043a\u0430 \u0431\u044b\u0441\u0442\u0440\u043e\u0439 \u0437\u0430\u0440\u044f\u0434\u043a\u0438", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "\u041f\u0440\u0430\u0433\u043c\u0430\u0442\u0438\u0447\u043d\u044b\u0439 \u043f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u043e\u043d\u0430\u043b", "point_of_view": "\u041c\u043e\u0431\u0438\u043b\u044c\u043d\u044b\u0439 \u0434\u0438\u0437\u0430\u0439\u043d\u0435\u0440-\u0444\u0440\u0438\u043b\u0430\u043d\u0441\u0435\u0440, \u0437\u0430\u0432\u0438\u0441\u044f\u0449\u0438\u0439 \u043e\u0442 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438 \u0438 \u0430\u0432\u0442\u043e\u043d\u043e\u043c\u043d\u043e\u0441\u0442\u0438", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.a1a341144c00be1328be6059d57bd123"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
Google Pixel 9 Pro
## Concept B
iPhone 14 Pro
## Aspect name
Автономность
## Aspect features
- Емкость аккумулятора
- Время автономной работы при активном испол ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.a1a341144c00be1328be6059d57bd123
other_notes: Сравнение основано на данных из авторитетных источников (официальные спецификации, обзоры). Для прагматичного профессионала, такого как мобильный дизайнер-фрилансер, общее время автономной работы может быть важнее номинальной емкости аккумулятора. iPhone 14 Pro демонстрирует более эффективное управление энергопотреблением, что приводит к лучшему времени работы при активном использовании, несмотря на меньшую емкость аккумулятора. Google Pixel 9 Pro предлагает более высокую номинальную емкость и более быструю зарядку, что может быть полезно для быстрого пополнения энергии в течение дня.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.8360e2ed4f0ee37d0f7db8c05e2b5699
process:
{"a_concept": "Google Pixel 9 Pro", "b_concept": "iPhone 14 Pro", "aspect_name": "\u042d\u043a\u0440\u0430\u043d", "aspect_features": "- \u0420\u0430\u0437\u0440\u0435\u0448\u0435\u043d\u0438\u0435 \u044d\u043a\u0440\u0430\u043d\u0430\n- \u0427\u0430\u0441\u0442\u043e\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f \u044d\u043a\u0440\u0430\u043d\u0430\n- \u042f\u0440\u043a\u043e\u0441\u0442\u044c", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "\u041f\u0440\u0430\u0433\u043c\u0430\u0442\u0438\u0447\u043d\u044b\u0439 \u043f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u043e\u043d\u0430\u043b", "point_of_view": "\u041c\u043e\u0431\u0438\u043b\u044c\u043d\u044b\u0439 \u0434\u0438\u0437\u0430\u0439\u043d\u0435\u0440-\u0444\u0440\u0438\u043b\u0430\u043d\u0441\u0435\u0440, \u0437\u0430\u0432\u0438\u0441\u044f\u0449\u0438\u0439 \u043e\u0442 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438 \u0438 \u0430\u0432\u0442\u043e\u043d\u043e\u043c\u043d\u043e\u0441\u0442\u0438", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.8360e2ed4f0ee37d0f7db8c05e2b5699"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
Google Pixel 9 Pro
## Concept B
iPhone 14 Pro
## Aspect name
Экран
## Aspect features
- Разрешение экрана
- Частота обновления экрана
- Яркость
## Observer stra ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.8360e2ed4f0ee37d0f7db8c05e2b5699
other_notes: С точки зрения прагматичного профессионала (мобильного дизайнера-фрилансера), важны не только числовые характеристики экрана, но и его точность цветопередачи, стабильность работы и влияние на автономность. Для дизайнера высокая яркость (пиковая) iPhone может быть полезна при работе на улице, но более высокое разрешение Pixel потенциально дает преимущество в детализации при создании и просмотре макетов. Частота обновления у обоих устройств высокая и адаптивная, что минимизирует разницу в восприятии плавности. В рамках объективной логической оценки сравнение проведено по заявленным производителями техническим спецификациям.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.f77f1b0357b997651eba18b7e48a16d0
process:
{"a_concept": "Google Pixel 9 Pro", "b_concept": "iPhone 14 Pro", "aspect_name": "\u0418\u043d\u0442\u0435\u0433\u0440\u0430\u0446\u0438\u044f \u0441 \u044d\u043a\u043e\u0441\u0438\u0441\u0442\u0435\u043c\u043e\u0439", "aspect_features": "- \u0411\u0435\u0441\u043f\u0440\u0435\u043f\u044f\u0442\u0441\u0442\u0432\u0435\u043d\u043d\u0430\u044f \u0441\u0438\u043d\u0445\u0440\u043e\u043d\u0438\u0437\u0430\u0446\u0438\u044f \u0441 \u041f\u041a/Mac\n- \u041f\u043e\u0434\u0434\u0435\u0440\u0436\u043a\u0430 \u043e\u0431\u043b\u0430\u0447\u043d\u044b\u0445 \u0441\u0435\u0440\u0432\u0438\u0441\u043e\u0432 \u0434\u043b\u044f \u0440\u0430\u0431\u043e\u0447\u0438\u0445 \u0444\u0430\u0439\u043b\u043e\u0432", "frame_of_reference": "Unbiased logic framework", "observer_strategy": "\u041f\u0440\u0430\u0433\u043c\u0430\u0442\u0438\u0447\u043d\u044b\u0439 \u043f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u043e\u043d\u0430\u043b", "point_of_view": "\u041c\u043e\u0431\u0438\u043b\u044c\u043d\u044b\u0439 \u0434\u0438\u0437\u0430\u0439\u043d\u0435\u0440-\u0444\u0440\u0438\u043b\u0430\u043d\u0441\u0435\u0440, \u0437\u0430\u0432\u0438\u0441\u044f\u0449\u0438\u0439 \u043e\u0442 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438 \u0438 \u0430\u0432\u0442\u043e\u043d\u043e\u043c\u043d\u043e\u0441\u0442\u0438", "_information_retrieval_strategy": "# Information retrieval strategy\nOnly_unbiased_authorative_sources: true", "_extra_output_specification": "# Extra output specification\nOutput_content_language: Russian", "meta": {"model": "deepseek/deepseek-chat"}, "process_type": "perspective_feature_comparison_af", "input_id": "perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.f77f1b0357b997651eba18b7e48a16d0"}
--- instruction meta: {"meta": {"model": "deepseek/deepseek-chat"}}
--- instruction:
Generate items strictly satisfying to:
* Target specification
* Information retrieval strategy
* Output generation strategy
* Output specification.

# Target specification
Task_description: to compare aspect values of given Concepts (A and B) for given Aspect features, Frame of reference, Observer strategy and Point of view.
## Concept A
Google Pixel 9 Pro
## Concept B
iPhone 14 Pro
## Aspect name
Интеграция с экосистемой
## Aspect features
- Беспрепятственная синхронизация с ПК/Mac
- Поддержка  ...

end: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.f77f1b0357b997651eba18b7e48a16d0
other_notes: С точки зрения прагматичного профессионала (мобильного дизайнера-фрилансера), экосистема Apple (iPhone) обеспечивает более глубокую и предсказуемую интеграцию между устройствами (Mac, iPhone, iPad), что критично для рабочих процессов. Экосистема Google (Pixel) более гибкая и кроссплатформенная, но может требовать дополнительных настроек. Оба устройства поддерживают основные облачные сервисы (Google Drive, iCloud), но выбор может зависеть от предпочтений в ПО. Для автономности и производительности, важных для фрилансера, оба флагмана сопоставимы, но интеграция с основной рабочей станцией (ПК/Mac) является ключевым фактором.
start: input_id=perspective_feature_comparison_af.2.7c4b139220d16dcec6ab5e8be56c4348.daf3298f64d47268f68ef4195313b45c
process:

In [18]:
d05_total_dt

,result_name,result_value
0,comparison_winner,iPhone 14 Pro
1,a_concept_score,-21%
2,b_concept_score,21%
3,LLM_model,deepseek/deepseek-chat
4,superordinate_concept,flagship smartphones
5,perspective_observer_strategy,Прагматичный профессионал
6,point_of_view,"Мобильный дизайнер-фрилансер, зависящий от про..."
7,observer_context_description,"Работаю фрилансером-дизайнером, много времени ..."
8,a_concept,Google Pixel 9 Pro
9,b_concept,iPhone 14 Pro

In [19]:
d05_aspect_dt

,type,aspect,feature,a_concept_winner,a_concept_score,b_concept_winner,b_concept_score
0,feature_score,Производительность и стабильность системы,Процессор,False,-,True,8%
1,feature_score,Производительность и стабильность системы,Оперативная память (ОЗУ),True,7%,False,-
2,feature_score,Производительность и стабильность системы,Стабильность операционной системы,False,-,True,9%
3,feature_score,Автономность,Емкость аккумулятора,True,7%,False,-
4,feature_score,Автономность,Время автономной работы при активном использов...,False,-,True,9%
5,feature_score,Автономность,Поддержка быстрой зарядки,True,6%,False,-
6,feature_score,Экран,Разрешение экрана,True,8%,False,-
7,feature_score,Экран,Частота обновления экрана,False,-,False,-
8,feature_score,Экран,Яркость,False,-,True,6%
9,feature_score,Интеграция с экосистемой,Беспрепятственная синхронизация с ПК/Mac,False,-,True,10%
10,feature_score,Интеграция с экосистемой,Поддержка облачных сервисов для рабочих файлов,False,-,False,-
11,feature_score,Камера,"Качество фотосъемки (динамический диапазон, де...",False,-,True,8%
12,feature_score,Камера,Поддержка форматов RAW для фото,False,-,False,-